# Generated by Django 5.2.9 on 2026-05-20 12:23

import common.db_fields.schema_field
import django.db.models.deletion
import japanese.enums.node_status
import japanese.enums.user_node_status
import japanese.schemas.kanji_schema
import japanese.schemas.particle_schema
import japanese.schemas.rule_schema
import japanese.schemas.sentence_schema
import japanese.schemas.word_schema
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sentence', 'sentence'), ('word', 'word'), ('kanji', 'kanji'), ('particle', 'particle'), ('rule', 'rule')], max_length=32)),
                ('status', models.CharField(blank=True, choices=[('stub', 'stub'), ('generating', 'generating'), ('needs_review', 'needs_review'), ('published', 'published')], default=japanese.enums.node_status.NodeStatus['STUB'], max_length=32)),
                ('canonical_key', models.CharField(max_length=255)),
                ('jlpt_level', models.CharField(blank=True, choices=[('n5', 'n5'), ('n4', 'n4'), ('n3', 'n3'), ('n2', 'n2'), ('n1', 'n1')], default=None, max_length=8, null=True)),
                ('content_html', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('sentence_data', common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=japanese.schemas.sentence_schema.SentenceSchema)),
                ('word_data', common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=japanese.schemas.word_schema.WordSchema)),
                ('kanji_data', common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=japanese.schemas.kanji_schema.KanjiSchema)),
                ('particle_data', common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=japanese.schemas.particle_schema.ParticleSchema)),
                ('rule_data', common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=japanese.schemas.rule_schema.RuleSchema)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'status'], name='japanese_no_type_38cd65_idx'), models.Index(fields=['status'], name='japanese_no_status_6292df_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'canonical_key'), name='japanese_node_unique_type_canonical_key')],
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_key', models.CharField(max_length=128)),
                ('model_used', models.CharField(max_length=128)),
                ('input_payload', models.TextField()),
                ('raw_output', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='japanese.node')),
            ],
            options={
                'indexes': [models.Index(fields=['node', '-generated_at'], name='japanese_ge_node_id_72ef7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('contains', 'contains'), ('composed_of', 'composed_of'), ('uses_rule', 'uses_rule'), ('example_of', 'example_of'), ('exception_to', 'exception_to'), ('synonym_of', 'synonym_of'), ('related_to', 'related_to'), ('same_kanji_as', 'same_kanji_as')], max_length=32)),
                ('edge_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='japanese.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='japanese.node')),
            ],
            options={
                'indexes': [models.Index(fields=['from_node', 'edge_type'], name='japanese_no_from_no_23fd98_idx'), models.Index(fields=['to_node', 'edge_type'], name='japanese_no_to_node_8d764b_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_node', 'to_node', 'edge_type'), name='japanese_nodeedge_unique_edge')],
            },
        ),
        migrations.CreateModel(
            name='UserNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('learning', 'learning'), ('mastered', 'mastered'), ('hidden', 'hidden')], default=japanese.enums.user_node_status.UserNodeStatus['LEARNING'], max_length=32)),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('next_review', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='japanese.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_node_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='japanese_us_user_id_c5d2dd_idx'), models.Index(fields=['next_review'], name='japanese_us_next_re_fef553_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'node'), name='japanese_usernodestate_unique_user_node')],
            },
        ),
    ]
