# Generated by Django 5.2.9 on 2026-06-17 17:45

import common.db_fields.schema_field
import japanese.schemas.passage_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='passage_data',
            field=common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=japanese.schemas.passage_schema.PassageSchema),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('passage', 'passage'), ('sentence', 'sentence'), ('word', 'word'), ('kanji', 'kanji'), ('particle', 'particle'), ('rule', 'rule')], max_length=32),
        ),
    ]
