// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateWorkoutExerciseViewData, CreateWorkoutExerciseViewResponses, CreateWorkoutRoutineViewData, CreateWorkoutRoutineViewResponses, DeleteWorkoutExerciseViewData, DeleteWorkoutExerciseViewResponses, DeleteWorkoutRoutineViewData, DeleteWorkoutRoutineViewResponses, GetWorkoutExerciseViewData, GetWorkoutExerciseViewResponses, GetWorkoutRoutineViewData, GetWorkoutRoutineViewResponses, PaginateWorkoutExercisesViewData, PaginateWorkoutExercisesViewResponses, PaginateWorkoutRoutinesViewData, PaginateWorkoutRoutinesViewResponses, UpdateWorkoutExerciseViewData, UpdateWorkoutExerciseViewResponses, UpdateWorkoutRoutineViewData, UpdateWorkoutRoutineViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateWorkoutRoutinesView = <ThrowOnError extends boolean = false>(options?: Options<PaginateWorkoutRoutinesViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateWorkoutRoutinesViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/routines/',
    ...options
});

/**
 * Post
 */
export const createWorkoutRoutineView = <ThrowOnError extends boolean = false>(options: Options<CreateWorkoutRoutineViewData, ThrowOnError>) => (options.client ?? client).post<CreateWorkoutRoutineViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/routines/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteWorkoutRoutineView = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkoutRoutineViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteWorkoutRoutineViewResponses, unknown, ThrowOnError>({
    url: '/api/workout-plan/routines/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getWorkoutRoutineView = <ThrowOnError extends boolean = false>(options: Options<GetWorkoutRoutineViewData, ThrowOnError>) => (options.client ?? client).get<GetWorkoutRoutineViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/routines/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateWorkoutRoutineView = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkoutRoutineViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateWorkoutRoutineViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/routines/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pagination
 */
export const paginateWorkoutExercisesView = <ThrowOnError extends boolean = false>(options: Options<PaginateWorkoutExercisesViewData, ThrowOnError>) => (options.client ?? client).get<PaginateWorkoutExercisesViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/routines/{routine_id}/exercises/',
    ...options
});

/**
 * Post
 */
export const createWorkoutExerciseView = <ThrowOnError extends boolean = false>(options: Options<CreateWorkoutExerciseViewData, ThrowOnError>) => (options.client ?? client).post<CreateWorkoutExerciseViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/exercises/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteWorkoutExerciseView = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkoutExerciseViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteWorkoutExerciseViewResponses, unknown, ThrowOnError>({
    url: '/api/workout-plan/exercises/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getWorkoutExerciseView = <ThrowOnError extends boolean = false>(options: Options<GetWorkoutExerciseViewData, ThrowOnError>) => (options.client ?? client).get<GetWorkoutExerciseViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/exercises/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateWorkoutExerciseView = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkoutExerciseViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateWorkoutExerciseViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/workout-plan/exercises/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
