// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateWorkoutRoutinesFilterSchema
 */
export type PaginateWorkoutRoutinesFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * PaginationOutput[WorkoutRoutineSchema]
 */
export type PaginationOutputWorkoutRoutineSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<WorkoutRoutineSchema>;
};

/**
 * WorkoutRoutineSchema
 */
export type WorkoutRoutineSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Order
     */
    order: number;
    /**
     * Exercise Count
     */
    exercise_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateWorkoutRoutineSchema
 */
export type CreateWorkoutRoutineSchema = {
    /**
     * Name
     */
    name: string;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateWorkoutRoutineSchema
 */
export type UpdateWorkoutRoutineSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Order
     */
    order?: number | null;
};

/**
 * PaginateWorkoutExercisesFilterSchema
 */
export type PaginateWorkoutExercisesFilterSchema = {
    [key: string]: unknown;
};

/**
 * ExercisesByRoutinePath
 */
export type ExercisesByRoutinePath = {
    /**
     * Routine Id
     */
    routine_id: number;
};

/**
 * ExerciseSetSchema
 */
export type ExerciseSetSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Order
     */
    order: number;
    /**
     * Reps
     */
    reps: number | null;
    /**
     * Duration Seconds
     */
    duration_seconds: number | null;
};

/**
 * MeasurementType
 */
export type MeasurementType = 'reps' | 'time';

/**
 * PaginationOutput[WorkoutExerciseSchema]
 */
export type PaginationOutputWorkoutExerciseSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<WorkoutExerciseSchema>;
};

/**
 * WorkoutExerciseSchema
 */
export type WorkoutExerciseSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Routine Id
     */
    routine_id: number;
    /**
     * Name
     */
    name: string;
    measurement_type: MeasurementType;
    /**
     * Notes
     */
    notes: string;
    /**
     * Order
     */
    order: number;
    /**
     * Sets
     */
    sets: Array<ExerciseSetSchema>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateWorkoutExerciseSchema
 */
export type CreateWorkoutExerciseSchema = {
    /**
     * Name
     */
    name: string;
    measurement_type?: MeasurementType | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Sets
     */
    sets?: Array<ExerciseSetWritableSchema> | null;
    /**
     * Routine Id
     */
    routine_id: number;
};

/**
 * ExerciseSetWritableSchema
 */
export type ExerciseSetWritableSchema = {
    /**
     * Reps
     */
    reps?: number | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
};

/**
 * WorkoutExerciseWritableSchema
 */
export type WorkoutExerciseWritableSchema = {
    /**
     * Name
     */
    name?: string | null;
    measurement_type?: MeasurementType | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Sets
     */
    sets?: Array<ExerciseSetWritableSchema> | null;
};

export type PaginateWorkoutRoutinesViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/workout-plan/routines/';
};

export type PaginateWorkoutRoutinesViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputWorkoutRoutineSchema;
};

export type PaginateWorkoutRoutinesViewResponse = PaginateWorkoutRoutinesViewResponses[keyof PaginateWorkoutRoutinesViewResponses];

export type CreateWorkoutRoutineViewData = {
    body: CreateWorkoutRoutineSchema;
    path?: never;
    query?: never;
    url: '/api/workout-plan/routines/';
};

export type CreateWorkoutRoutineViewResponses = {
    /**
     * OK
     */
    200: WorkoutRoutineSchema;
};

export type CreateWorkoutRoutineViewResponse = CreateWorkoutRoutineViewResponses[keyof CreateWorkoutRoutineViewResponses];

export type DeleteWorkoutRoutineViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/workout-plan/routines/{object_id}/';
};

export type DeleteWorkoutRoutineViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkoutRoutineViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/workout-plan/routines/{object_id}/';
};

export type GetWorkoutRoutineViewResponses = {
    /**
     * OK
     */
    200: WorkoutRoutineSchema;
};

export type GetWorkoutRoutineViewResponse = GetWorkoutRoutineViewResponses[keyof GetWorkoutRoutineViewResponses];

export type UpdateWorkoutRoutineViewData = {
    body: UpdateWorkoutRoutineSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/workout-plan/routines/{object_id}/';
};

export type UpdateWorkoutRoutineViewResponses = {
    /**
     * OK
     */
    200: WorkoutRoutineSchema;
};

export type UpdateWorkoutRoutineViewResponse = UpdateWorkoutRoutineViewResponses[keyof UpdateWorkoutRoutineViewResponses];

export type PaginateWorkoutExercisesViewData = {
    body?: never;
    path: {
        /**
         * Routine Id
         */
        routine_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/workout-plan/routines/{routine_id}/exercises/';
};

export type PaginateWorkoutExercisesViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputWorkoutExerciseSchema;
};

export type PaginateWorkoutExercisesViewResponse = PaginateWorkoutExercisesViewResponses[keyof PaginateWorkoutExercisesViewResponses];

export type CreateWorkoutExerciseViewData = {
    body: CreateWorkoutExerciseSchema;
    path?: never;
    query?: never;
    url: '/api/workout-plan/exercises/';
};

export type CreateWorkoutExerciseViewResponses = {
    /**
     * OK
     */
    200: WorkoutExerciseSchema;
};

export type CreateWorkoutExerciseViewResponse = CreateWorkoutExerciseViewResponses[keyof CreateWorkoutExerciseViewResponses];

export type DeleteWorkoutExerciseViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/workout-plan/exercises/{object_id}/';
};

export type DeleteWorkoutExerciseViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkoutExerciseViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/workout-plan/exercises/{object_id}/';
};

export type GetWorkoutExerciseViewResponses = {
    /**
     * OK
     */
    200: WorkoutExerciseSchema;
};

export type GetWorkoutExerciseViewResponse = GetWorkoutExerciseViewResponses[keyof GetWorkoutExerciseViewResponses];

export type UpdateWorkoutExerciseViewData = {
    body: WorkoutExerciseWritableSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/workout-plan/exercises/{object_id}/';
};

export type UpdateWorkoutExerciseViewResponses = {
    /**
     * OK
     */
    200: WorkoutExerciseSchema;
};

export type UpdateWorkoutExerciseViewResponse = UpdateWorkoutExerciseViewResponses[keyof UpdateWorkoutExerciseViewResponses];
