// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthViewData, AuthViewResponses, ChangePasswordByAccessIdViewData, ChangePasswordByAccessIdViewResponses, ChangePasswordViewData, ChangePasswordViewResponses, CheckTemporaryAccessViewData, CheckTemporaryAccessViewResponses, ForgotMyPasswordViewData, ForgotMyPasswordViewResponses, GoogleLoginViewData, GoogleLoginViewResponses, LoginViewData, LoginViewResponses, LogoutViewData, LogoutViewResponses, WebAuthnCredentialsViewData, WebAuthnCredentialsViewResponses, WebAuthnDeleteCredentialViewData, WebAuthnDeleteCredentialViewResponses, WebAuthnLoginOptionsViewData, WebAuthnLoginOptionsViewResponses, WebAuthnLoginVerifyViewData, WebAuthnLoginVerifyViewResponses, WebAuthnRegisterOptionsViewData, WebAuthnRegisterOptionsViewResponses, WebAuthnRegisterVerifyViewData, WebAuthnRegisterVerifyViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const authView = <ThrowOnError extends boolean = false>(options?: Options<AuthViewData, ThrowOnError>) => (options?.client ?? client).get<AuthViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/',
    ...options
});

/**
 * Get
 */
export const loginView = <ThrowOnError extends boolean = false>(options: Options<LoginViewData, ThrowOnError>) => (options.client ?? client).post<LoginViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const googleLoginView = <ThrowOnError extends boolean = false>(options: Options<GoogleLoginViewData, ThrowOnError>) => (options.client ?? client).post<GoogleLoginViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/google-login/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const logoutView = <ThrowOnError extends boolean = false>(options?: Options<LogoutViewData, ThrowOnError>) => (options?.client ?? client).post<LogoutViewResponses, unknown, ThrowOnError>({ url: '/auth/logout/', ...options });

/**
 * Post
 */
export const changePasswordView = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordViewData, ThrowOnError>) => (options.client ?? client).post<ChangePasswordViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/change-password/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const checkTemporaryAccessView = <ThrowOnError extends boolean = false>(options: Options<CheckTemporaryAccessViewData, ThrowOnError>) => (options.client ?? client).post<CheckTemporaryAccessViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/check-temporary-access/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const forgotMyPasswordView = <ThrowOnError extends boolean = false>(options: Options<ForgotMyPasswordViewData, ThrowOnError>) => (options.client ?? client).post<ForgotMyPasswordViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/forgot-my-password/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const changePasswordByAccessIdView = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordByAccessIdViewData, ThrowOnError>) => (options.client ?? client).post<ChangePasswordByAccessIdViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/change-password-by-access-id/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const webAuthnRegisterOptionsView = <ThrowOnError extends boolean = false>(options?: Options<WebAuthnRegisterOptionsViewData, ThrowOnError>) => (options?.client ?? client).get<WebAuthnRegisterOptionsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/webauthn/register-options/',
    ...options
});

/**
 * Post
 */
export const webAuthnRegisterVerifyView = <ThrowOnError extends boolean = false>(options: Options<WebAuthnRegisterVerifyViewData, ThrowOnError>) => (options.client ?? client).post<WebAuthnRegisterVerifyViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/webauthn/register-verify/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const webAuthnLoginOptionsView = <ThrowOnError extends boolean = false>(options?: Options<WebAuthnLoginOptionsViewData, ThrowOnError>) => (options?.client ?? client).get<WebAuthnLoginOptionsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/webauthn/login-options/',
    ...options
});

/**
 * Post
 */
export const webAuthnLoginVerifyView = <ThrowOnError extends boolean = false>(options: Options<WebAuthnLoginVerifyViewData, ThrowOnError>) => (options.client ?? client).post<WebAuthnLoginVerifyViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/webauthn/login-verify/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const webAuthnCredentialsView = <ThrowOnError extends boolean = false>(options?: Options<WebAuthnCredentialsViewData, ThrowOnError>) => (options?.client ?? client).get<WebAuthnCredentialsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/webauthn/credentials/',
    ...options
});

/**
 * Post
 */
export const webAuthnDeleteCredentialView = <ThrowOnError extends boolean = false>(options: Options<WebAuthnDeleteCredentialViewData, ThrowOnError>) => (options.client ?? client).post<WebAuthnDeleteCredentialViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/webauthn/delete-credential/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
