// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * AuthSchema
 */
export type AuthSchema = {
    /**
     * Is Authenticated
     */
    is_authenticated: boolean;
    /**
     * Msg
     */
    msg?: string | null;
    user?: UserSchema | null;
    /**
     * Access Token
     */
    access_token?: string | null;
};

/**
 * Permissions
 */
export type Permissions = 'admin' | 'editor';

/**
 * SubscriptionLimitsSchema
 */
export type SubscriptionLimitsSchema = {
    /**
     * Items
     */
    items: number;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Pic Url
     */
    pic_url: string | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Initials
     */
    initials: string;
    /**
     * Permissions
     */
    permissions: Array<Permissions>;
    subscription_limits: SubscriptionLimitsSchema;
    /**
     * Has Usable Password
     */
    has_usable_password: boolean;
};

/**
 * LoginSchema
 */
export type LoginSchema = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * GoogleLoginSchema
 */
export type GoogleLoginSchema = {
    /**
     * Google Code
     */
    google_code: string;
};

/**
 * ChangePasswordOutputSchema
 */
export type ChangePasswordOutputSchema = {
    /**
     * Is Success
     */
    is_success: boolean;
    /**
     * Msg
     */
    msg: string;
};

/**
 * ChangePasswordInputSchema
 */
export type ChangePasswordInputSchema = {
    /**
     * Old Password
     */
    old_password?: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * CheckTemporaryAccessSchema
 */
export type CheckTemporaryAccessSchema = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Access Id
     */
    access_id: string;
};

/**
 * ForgotMyPasswordSchema
 */
export type ForgotMyPasswordSchema = {
    /**
     * Email
     */
    email: string;
};

/**
 * ChangePasswordByAccessIdSchema
 */
export type ChangePasswordByAccessIdSchema = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Access Id
     */
    access_id: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * RegistrationOptionsSchema
 */
export type RegistrationOptionsSchema = {
    /**
     * Challenge
     */
    challenge: string;
    /**
     * Rp
     */
    rp: {
        [key: string]: unknown;
    };
    /**
     * User
     */
    user: {
        [key: string]: unknown;
    };
    /**
     * Pubkeycredparams
     */
    pubKeyCredParams: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Timeout
     */
    timeout?: number | null;
    /**
     * Attestation
     */
    attestation?: string | null;
    /**
     * Authenticatorselection
     */
    authenticatorSelection?: {
        [key: string]: unknown;
    } | null;
    /**
     * Excludecredentials
     */
    excludeCredentials?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * AttestationResponseInput
 */
export type AttestationResponseInput = {
    /**
     * Clientdatajson
     */
    clientDataJSON: string;
    /**
     * Attestationobject
     */
    attestationObject: string;
    /**
     * Transports
     */
    transports?: Array<string> | null;
};

/**
 * RegistrationVerifyInput
 */
export type RegistrationVerifyInput = {
    /**
     * Id
     */
    id: string;
    /**
     * Rawid
     */
    rawId: string;
    /**
     * Type
     */
    type: string;
    response: AttestationResponseInput;
};

/**
 * LoginOptionsSchema
 */
export type LoginOptionsSchema = {
    /**
     * Challenge
     */
    challenge: string;
    /**
     * Rpid
     */
    rpId?: string | null;
    /**
     * Timeout
     */
    timeout?: number | null;
    /**
     * Allowcredentials
     */
    allowCredentials?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Userverification
     */
    userVerification?: string | null;
};

/**
 * AssertionResponseInput
 */
export type AssertionResponseInput = {
    /**
     * Clientdatajson
     */
    clientDataJSON: string;
    /**
     * Authenticatordata
     */
    authenticatorData: string;
    /**
     * Signature
     */
    signature: string;
    /**
     * Userhandle
     */
    userHandle?: string | null;
};

/**
 * LoginVerifyInput
 */
export type LoginVerifyInput = {
    /**
     * Id
     */
    id: string;
    /**
     * Rawid
     */
    rawId: string;
    /**
     * Type
     */
    type: string;
    response: AssertionResponseInput;
};

/**
 * CredentialsSchema
 */
export type CredentialsSchema = {
    /**
     * Has Passkey
     */
    has_passkey: boolean;
    /**
     * Credentials
     */
    credentials: Array<WebAuthnCredentialInfo>;
};

/**
 * WebAuthnCredentialInfo
 */
export type WebAuthnCredentialInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Credential Id
     */
    credential_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DeleteCredentialOutput
 */
export type DeleteCredentialOutput = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * DeleteCredentialInput
 */
export type DeleteCredentialInput = {
    /**
     * Credential Id
     */
    credential_id: string;
};

export type AuthViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/';
};

export type AuthViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type AuthViewResponse = AuthViewResponses[keyof AuthViewResponses];

export type LoginViewData = {
    body: LoginSchema;
    path?: never;
    query?: never;
    url: '/auth/login/';
};

export type LoginViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type LoginViewResponse = LoginViewResponses[keyof LoginViewResponses];

export type GoogleLoginViewData = {
    body: GoogleLoginSchema;
    path?: never;
    query?: never;
    url: '/auth/google-login/';
};

export type GoogleLoginViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type GoogleLoginViewResponse = GoogleLoginViewResponses[keyof GoogleLoginViewResponses];

export type LogoutViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout/';
};

export type LogoutViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ChangePasswordViewData = {
    body: ChangePasswordInputSchema;
    path?: never;
    query?: never;
    url: '/auth/change-password/';
};

export type ChangePasswordViewResponses = {
    /**
     * OK
     */
    200: ChangePasswordOutputSchema;
};

export type ChangePasswordViewResponse = ChangePasswordViewResponses[keyof ChangePasswordViewResponses];

export type CheckTemporaryAccessViewData = {
    body: CheckTemporaryAccessSchema;
    path?: never;
    query?: never;
    url: '/auth/check-temporary-access/';
};

export type CheckTemporaryAccessViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type CheckTemporaryAccessViewResponse = CheckTemporaryAccessViewResponses[keyof CheckTemporaryAccessViewResponses];

export type ForgotMyPasswordViewData = {
    body: ForgotMyPasswordSchema;
    path?: never;
    query?: never;
    url: '/auth/forgot-my-password/';
};

export type ForgotMyPasswordViewResponses = {
    /**
     * OK
     */
    200: EmptySchema;
};

export type ForgotMyPasswordViewResponse = ForgotMyPasswordViewResponses[keyof ForgotMyPasswordViewResponses];

export type ChangePasswordByAccessIdViewData = {
    body: ChangePasswordByAccessIdSchema;
    path?: never;
    query?: never;
    url: '/auth/change-password-by-access-id/';
};

export type ChangePasswordByAccessIdViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type ChangePasswordByAccessIdViewResponse = ChangePasswordByAccessIdViewResponses[keyof ChangePasswordByAccessIdViewResponses];

export type WebAuthnRegisterOptionsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/webauthn/register-options/';
};

export type WebAuthnRegisterOptionsViewResponses = {
    /**
     * OK
     */
    200: RegistrationOptionsSchema;
};

export type WebAuthnRegisterOptionsViewResponse = WebAuthnRegisterOptionsViewResponses[keyof WebAuthnRegisterOptionsViewResponses];

export type WebAuthnRegisterVerifyViewData = {
    body: RegistrationVerifyInput;
    path?: never;
    query?: never;
    url: '/auth/webauthn/register-verify/';
};

export type WebAuthnRegisterVerifyViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type WebAuthnRegisterVerifyViewResponse = WebAuthnRegisterVerifyViewResponses[keyof WebAuthnRegisterVerifyViewResponses];

export type WebAuthnLoginOptionsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/webauthn/login-options/';
};

export type WebAuthnLoginOptionsViewResponses = {
    /**
     * OK
     */
    200: LoginOptionsSchema;
};

export type WebAuthnLoginOptionsViewResponse = WebAuthnLoginOptionsViewResponses[keyof WebAuthnLoginOptionsViewResponses];

export type WebAuthnLoginVerifyViewData = {
    body: LoginVerifyInput;
    path?: never;
    query?: never;
    url: '/auth/webauthn/login-verify/';
};

export type WebAuthnLoginVerifyViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type WebAuthnLoginVerifyViewResponse = WebAuthnLoginVerifyViewResponses[keyof WebAuthnLoginVerifyViewResponses];

export type WebAuthnCredentialsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/webauthn/credentials/';
};

export type WebAuthnCredentialsViewResponses = {
    /**
     * OK
     */
    200: CredentialsSchema;
};

export type WebAuthnCredentialsViewResponse = WebAuthnCredentialsViewResponses[keyof WebAuthnCredentialsViewResponses];

export type WebAuthnDeleteCredentialViewData = {
    body: DeleteCredentialInput;
    path?: never;
    query?: never;
    url: '/auth/webauthn/delete-credential/';
};

export type WebAuthnDeleteCredentialViewResponses = {
    /**
     * OK
     */
    200: DeleteCredentialOutput;
};

export type WebAuthnDeleteCredentialViewResponse = WebAuthnDeleteCredentialViewResponses[keyof WebAuthnDeleteCredentialViewResponses];
