from common.django_utils.api_router_creator import ApiRouterCreator
from dream_diary.permissions_checkers.dream_diary_permission_checker import DreamDiaryPermissionChecker
from dream_diary.views.dream_diary_calendar_views.get_dream_diary_calendar_view import GetDreamDiaryCalendarView
from dream_diary.views.dream_diary_entry_views.create_dream_diary_entry_view import CreateDreamDiaryEntryView
from dream_diary.views.dream_diary_entry_views.delete_dream_diary_entry_view import DeleteDreamDiaryEntryView
from dream_diary.views.dream_diary_entry_views.generate_dream_diary_entry_image_view import GenerateDreamDiaryEntryImageView
from dream_diary.views.dream_diary_entry_views.get_dream_diary_entry_view import GetDreamDiaryEntryView
from dream_diary.views.dream_diary_entry_views.paginate_dream_diary_entries_view import PaginateDreamDiaryEntriesView
from dream_diary.views.dream_diary_entry_views.update_dream_diary_entry_view import UpdateDreamDiaryEntryView
from dream_diary.views.dream_diary_entry_views.upload_dream_diary_entry_image_view import UploadDreamDiaryEntryImageView

api, router = ApiRouterCreator.create_api_and_router('dream-diary', DreamDiaryPermissionChecker())

PaginateDreamDiaryEntriesView.register_get(router, '')
GetDreamDiaryEntryView.register_get_by_id(router)
CreateDreamDiaryEntryView.register_post(router)
UpdateDreamDiaryEntryView.register_patch_by_id(router)
DeleteDreamDiaryEntryView.register_delete_by_id(router)
UploadDreamDiaryEntryImageView.register_post_by_id(router, 'upload-image/')
GenerateDreamDiaryEntryImageView.register_post_by_id(router, 'generate-image/')

GetDreamDiaryCalendarView.register_get(router, 'calendar/')
