// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRenterProspectViewData, CreateRenterProspectViewResponses, CreateRentersProjectViewData, CreateRentersProjectViewResponses, DeleteRentalProjectViewData, DeleteRentalProjectViewResponses, DeleteRenterProspectViewData, DeleteRenterProspectViewResponses, FinishRentalProjectViewData, FinishRentalProjectViewResponses, GetRentalProjectViewData, GetRentalProjectViewResponses, GetRenterProspectViewData, GetRenterProspectViewResponses, ListProjectMembersViewData, ListProjectMembersViewResponses, PaginateRenterProspectsViewData, PaginateRenterProspectsViewResponses, PaginateRentersProjectsViewData, PaginateRentersProjectsViewResponses, ReopenRentalProjectViewData, ReopenRentalProjectViewResponses, ShareRentalProjectViewData, ShareRentalProjectViewResponses, UnshareRentalProjectViewData, UnshareRentalProjectViewResponses, UpdateRentalProjectViewData, UpdateRentalProjectViewResponses, UpdateRenterProspectViewData, UpdateRenterProspectViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateRentersProjectsView = <ThrowOnError extends boolean = false>(options?: Options<PaginateRentersProjectsViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateRentersProjectsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/',
    ...options
});

/**
 * Post
 */
export const createRentersProjectView = <ThrowOnError extends boolean = false>(options: Options<CreateRentersProjectViewData, ThrowOnError>) => (options.client ?? client).post<CreateRentersProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<DeleteRentalProjectViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteRentalProjectViewResponses, unknown, ThrowOnError>({
    url: '/api/renters-crm/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<GetRentalProjectViewData, ThrowOnError>) => (options.client ?? client).get<GetRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<UpdateRentalProjectViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const shareRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<ShareRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<ShareRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/share/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unshareRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<UnshareRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<UnshareRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/unshare/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const listProjectMembersView = <ThrowOnError extends boolean = false>(options: Options<ListProjectMembersViewData, ThrowOnError>) => (options.client ?? client).get<ListProjectMembersViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/members/',
    ...options
});

/**
 * Post
 */
export const finishRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<FinishRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<FinishRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/finish/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const reopenRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<ReopenRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<ReopenRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{object_id}/reopen/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pagination
 */
export const paginateRenterProspectsView = <ThrowOnError extends boolean = false>(options: Options<PaginateRenterProspectsViewData, ThrowOnError>) => (options.client ?? client).get<PaginateRenterProspectsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/projects/{project_id}/renters/',
    ...options
});

/**
 * Post
 */
export const createRenterProspectView = <ThrowOnError extends boolean = false>(options: Options<CreateRenterProspectViewData, ThrowOnError>) => (options.client ?? client).post<CreateRenterProspectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/renters/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteRenterProspectView = <ThrowOnError extends boolean = false>(options: Options<DeleteRenterProspectViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteRenterProspectViewResponses, unknown, ThrowOnError>({
    url: '/api/renters-crm/renters/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getRenterProspectView = <ThrowOnError extends boolean = false>(options: Options<GetRenterProspectViewData, ThrowOnError>) => (options.client ?? client).get<GetRenterProspectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/renters/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateRenterProspectView = <ThrowOnError extends boolean = false>(options: Options<UpdateRenterProspectViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateRenterProspectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/renters-crm/renters/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
