// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateRentalProjectsFilterSchema
 */
export type PaginateRentalProjectsFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * Currency
 */
export type Currency = 'nis' | 'usd' | 'eur' | 'gbp';

/**
 * PaginationOutput[RentalProjectSchema]
 */
export type PaginationOutputRentalProjectSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<RentalProjectSchema>;
};

/**
 * ProjectApp
 */
export type ProjectApp = 'apartment_hunt' | 'renters_crm' | 'villa_villekulla';

/**
 * ProjectStatus
 */
export type ProjectStatus = 'active' | 'finished';

/**
 * RentalProjectSchema
 */
export type RentalProjectSchema = {
    /**
     * Id
     */
    id: number;
    app: ProjectApp;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    currency: Currency;
    status: ProjectStatus;
    /**
     * Initial Asked Rent
     */
    initial_asked_rent: number | null;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Owner Username
     */
    owner_username: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateRentalProjectSchema
 */
export type CreateRentalProjectSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    currency?: Currency;
    /**
     * Initial Asked Rent
     */
    initial_asked_rent?: number | string | null;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateRentalProjectSchema
 */
export type UpdateRentalProjectSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    currency?: Currency | null;
    /**
     * Initial Asked Rent
     */
    initial_asked_rent?: number | string | null;
};

/**
 * ProjectRole
 */
export type ProjectRole = 'owner' | 'collaborator';

/**
 * ShareRentalProjectSchema
 */
export type ShareRentalProjectSchema = {
    /**
     * Identifier
     */
    identifier: string;
    role?: ProjectRole;
};

/**
 * UnshareRentalProjectSchema
 */
export type UnshareRentalProjectSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * ProjectMembersSchema
 */
export type ProjectMembersSchema = {
    /**
     * Members
     */
    members: Array<ProjectMembershipSchema>;
};

/**
 * ProjectMembershipSchema
 */
export type ProjectMembershipSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name: string;
    role: ProjectRole;
};

/**
 * PaginateRenterProspectsFilterSchema
 */
export type PaginateRenterProspectsFilterSchema = {
    /**
     * Status
     */
    status?: string | null;
};

/**
 * RenterProspectsByProjectPath
 */
export type RenterProspectsByProjectPath = {
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * FamilyStatus
 */
export type FamilyStatus = 'family_with_children' | 'couple' | 'single';

/**
 * PaginationOutput[RenterProspectSchema]
 */
export type PaginationOutputRenterProspectSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<RenterProspectSchema>;
};

/**
 * RenterProspectSchema
 */
export type RenterProspectSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Name
     */
    name: string;
    status: RenterStatus;
    /**
     * Saw Apartment
     */
    saw_apartment: boolean;
    /**
     * Visit Time
     */
    visit_time: string | null;
    /**
     * Has Animals
     */
    has_animals: boolean;
    /**
     * Long Term
     */
    long_term: boolean;
    family_status: FamilyStatus;
    /**
     * Notes
     */
    notes: string;
    /**
     * Agreed Rent
     */
    agreed_rent: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RenterStatus
 */
export type RenterStatus = 'contacted' | 'scheduled_to_see' | 'visited' | 'declined' | 'want_to_sign' | 'signed';

/**
 * CreateRenterProspectSchema
 */
export type CreateRenterProspectSchema = {
    /**
     * Name
     */
    name?: string | null;
    status?: RenterStatus | null;
    /**
     * Saw Apartment
     */
    saw_apartment?: boolean | null;
    /**
     * Visit Time
     */
    visit_time?: string | null;
    /**
     * Has Animals
     */
    has_animals?: boolean | null;
    /**
     * Long Term
     */
    long_term?: boolean | null;
    family_status?: FamilyStatus | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Agreed Rent
     */
    agreed_rent?: number | string | null;
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * RenterProspectWritableSchema
 */
export type RenterProspectWritableSchema = {
    /**
     * Name
     */
    name?: string | null;
    status?: RenterStatus | null;
    /**
     * Saw Apartment
     */
    saw_apartment?: boolean | null;
    /**
     * Visit Time
     */
    visit_time?: string | null;
    /**
     * Has Animals
     */
    has_animals?: boolean | null;
    /**
     * Long Term
     */
    long_term?: boolean | null;
    family_status?: FamilyStatus | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Agreed Rent
     */
    agreed_rent?: number | string | null;
};

export type PaginateRentersProjectsViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/renters-crm/projects/';
};

export type PaginateRentersProjectsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputRentalProjectSchema;
};

export type PaginateRentersProjectsViewResponse = PaginateRentersProjectsViewResponses[keyof PaginateRentersProjectsViewResponses];

export type CreateRentersProjectViewData = {
    body: CreateRentalProjectSchema;
    path?: never;
    query?: never;
    url: '/api/renters-crm/projects/';
};

export type CreateRentersProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type CreateRentersProjectViewResponse = CreateRentersProjectViewResponses[keyof CreateRentersProjectViewResponses];

export type DeleteRentalProjectViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/';
};

export type DeleteRentalProjectViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRentalProjectViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/';
};

export type GetRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type GetRentalProjectViewResponse = GetRentalProjectViewResponses[keyof GetRentalProjectViewResponses];

export type UpdateRentalProjectViewData = {
    body: UpdateRentalProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/';
};

export type UpdateRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type UpdateRentalProjectViewResponse = UpdateRentalProjectViewResponses[keyof UpdateRentalProjectViewResponses];

export type ShareRentalProjectViewData = {
    body: ShareRentalProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/share/';
};

export type ShareRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type ShareRentalProjectViewResponse = ShareRentalProjectViewResponses[keyof ShareRentalProjectViewResponses];

export type UnshareRentalProjectViewData = {
    body: UnshareRentalProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/unshare/';
};

export type UnshareRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type UnshareRentalProjectViewResponse = UnshareRentalProjectViewResponses[keyof UnshareRentalProjectViewResponses];

export type ListProjectMembersViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/members/';
};

export type ListProjectMembersViewResponses = {
    /**
     * OK
     */
    200: ProjectMembersSchema;
};

export type ListProjectMembersViewResponse = ListProjectMembersViewResponses[keyof ListProjectMembersViewResponses];

export type FinishRentalProjectViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/finish/';
};

export type FinishRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type FinishRentalProjectViewResponse = FinishRentalProjectViewResponses[keyof FinishRentalProjectViewResponses];

export type ReopenRentalProjectViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/projects/{object_id}/reopen/';
};

export type ReopenRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type ReopenRentalProjectViewResponse = ReopenRentalProjectViewResponses[keyof ReopenRentalProjectViewResponses];

export type PaginateRenterProspectsViewData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/renters-crm/projects/{project_id}/renters/';
};

export type PaginateRenterProspectsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputRenterProspectSchema;
};

export type PaginateRenterProspectsViewResponse = PaginateRenterProspectsViewResponses[keyof PaginateRenterProspectsViewResponses];

export type CreateRenterProspectViewData = {
    body: CreateRenterProspectSchema;
    path?: never;
    query?: never;
    url: '/api/renters-crm/renters/';
};

export type CreateRenterProspectViewResponses = {
    /**
     * OK
     */
    200: RenterProspectSchema;
};

export type CreateRenterProspectViewResponse = CreateRenterProspectViewResponses[keyof CreateRenterProspectViewResponses];

export type DeleteRenterProspectViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/renters/{object_id}/';
};

export type DeleteRenterProspectViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRenterProspectViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/renters/{object_id}/';
};

export type GetRenterProspectViewResponses = {
    /**
     * OK
     */
    200: RenterProspectSchema;
};

export type GetRenterProspectViewResponse = GetRenterProspectViewResponses[keyof GetRenterProspectViewResponses];

export type UpdateRenterProspectViewData = {
    body: RenterProspectWritableSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/renters-crm/renters/{object_id}/';
};

export type UpdateRenterProspectViewResponses = {
    /**
     * OK
     */
    200: RenterProspectSchema;
};

export type UpdateRenterProspectViewResponse = UpdateRenterProspectViewResponses[keyof UpdateRenterProspectViewResponses];
