# Generated by Django 5.2.9 on 2026-03-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campaigns_limit',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
