# Generated by Django 5.2.9 on 2026-05-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_webauthnchallenge_webauthncredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
