# Generated by Django 5.2.9 on 2026-06-22 08:46

import common.db_fields.list_field_with_choices
import common.db_fields.schema_field
import common.time_utils
import django.db.models.deletion
import users.enums.invitation_status
import users.models.invitation
import users.schemas.invitation_schema
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('permissions', common.db_fields.list_field_with_choices.ListFieldWithChoices(base_field=models.CharField(blank=True, choices=[], max_length=100, null=True), blank=True, default=list, size=None)),
                ('membership', common.db_fields.schema_field.SchemaField(blank=True, default=None, many=False, null=True, schema=users.schemas.invitation_schema.InvitationMembership)),
                ('token', models.CharField(blank=True, default=users.models.invitation.get_random_token, max_length=24)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted')], default=users.enums.invitation_status.InvitationStatus['PENDING'], max_length=16)),
                ('created_at', models.DateTimeField(default=common.time_utils.TimeUtils.now)),
                ('accepted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
