// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ConvertSpecialDateViewData, ConvertSpecialDateViewResponses, CreateSpecialDateViewData, CreateSpecialDateViewResponses, DeleteSpecialDateViewData, DeleteSpecialDateViewResponses, GetHebrewYearViewData, GetHebrewYearViewResponses, GetUpcomingSpecialDatesViewData, GetUpcomingSpecialDatesViewResponses, PaginateSpecialDatesViewData, PaginateSpecialDatesViewResponses, UpdateSpecialDateViewData, UpdateSpecialDateViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateSpecialDatesView = <ThrowOnError extends boolean = false>(options?: Options<PaginateSpecialDatesViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateSpecialDatesViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/special-dates/dates/',
    ...options
});

/**
 * Post
 */
export const createSpecialDateView = <ThrowOnError extends boolean = false>(options: Options<CreateSpecialDateViewData, ThrowOnError>) => (options.client ?? client).post<CreateSpecialDateViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/special-dates/dates/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteSpecialDateView = <ThrowOnError extends boolean = false>(options: Options<DeleteSpecialDateViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteSpecialDateViewResponses, unknown, ThrowOnError>({
    url: '/api/special-dates/dates/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Patch
 */
export const updateSpecialDateView = <ThrowOnError extends boolean = false>(options: Options<UpdateSpecialDateViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateSpecialDateViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/special-dates/dates/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getUpcomingSpecialDatesView = <ThrowOnError extends boolean = false>(options?: Options<GetUpcomingSpecialDatesViewData, ThrowOnError>) => (options?.client ?? client).get<GetUpcomingSpecialDatesViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/special-dates/upcoming/',
    ...options
});

/**
 * Get
 */
export const convertSpecialDateView = <ThrowOnError extends boolean = false>(options: Options<ConvertSpecialDateViewData, ThrowOnError>) => (options.client ?? client).get<ConvertSpecialDateViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/special-dates/convert/',
    ...options
});

/**
 * Get
 */
export const getHebrewYearView = <ThrowOnError extends boolean = false>(options: Options<GetHebrewYearViewData, ThrowOnError>) => (options.client ?? client).get<GetHebrewYearViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/special-dates/hebrew-year/',
    ...options
});
