// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateSpecialDatesFilterSchema
 */
export type PaginateSpecialDatesFilterSchema = {
    /**
     * Search
     */
    search?: string | null;
    category?: SpecialDateCategory | null;
    /**
     * Calendar Id
     */
    calendar_id?: number | null;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * SpecialDateCategory
 */
export type SpecialDateCategory = 'birthday' | 'anniversary' | 'memorial' | 'other';

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * CalendarType
 */
export type CalendarType = 'gregorian' | 'hebrew';

/**
 * PaginationOutput[SpecialDateSchema]
 */
export type PaginationOutputSpecialDateSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<SpecialDateSchema>;
};

/**
 * SpecialDateSchema
 */
export type SpecialDateSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Calendar Id
     */
    calendar_id: number | null;
    /**
     * Created By Name
     */
    created_by_name: string;
    /**
     * Name
     */
    name: string;
    category: SpecialDateCategory;
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset: boolean;
    input_calendar: CalendarType;
    /**
     * Hebrew Year
     */
    hebrew_year: number;
    /**
     * Hebrew Month
     */
    hebrew_month: number;
    /**
     * Hebrew Day
     */
    hebrew_day: number;
    /**
     * Hebrew Date
     */
    hebrew_date: string;
    /**
     * Remind Hebrew
     */
    remind_hebrew: boolean;
    /**
     * Remind Gregorian
     */
    remind_gregorian: boolean;
    /**
     * Next Gregorian Date
     */
    next_gregorian_date: string | null;
    /**
     * Next Hebrew Date
     */
    next_hebrew_date: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateSpecialDateSchema
 */
export type CreateSpecialDateSchema = {
    /**
     * Calendar Id
     */
    calendar_id: number;
    /**
     * Name
     */
    name: string;
    category: SpecialDateCategory;
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset?: boolean;
    input_calendar?: CalendarType;
    /**
     * Remind Hebrew
     */
    remind_hebrew?: boolean;
    /**
     * Remind Gregorian
     */
    remind_gregorian?: boolean;
};

/**
 * MoveSpecialDatesSchema
 */
export type MoveSpecialDatesSchema = {
    /**
     * Special Date Ids
     */
    special_date_ids: Array<number>;
    /**
     * Calendar Id
     */
    calendar_id: number;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateSpecialDateSchema
 */
export type UpdateSpecialDateSchema = {
    /**
     * Calendar Id
     */
    calendar_id?: number | null;
    /**
     * Name
     */
    name?: string | null;
    category?: SpecialDateCategory | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * After Sunset
     */
    after_sunset?: boolean | null;
    input_calendar?: CalendarType | null;
    /**
     * Remind Hebrew
     */
    remind_hebrew?: boolean | null;
    /**
     * Remind Gregorian
     */
    remind_gregorian?: boolean | null;
};

/**
 * SpecialDateOccurrenceSchema
 */
export type SpecialDateOccurrenceSchema = {
    special_date: SpecialDateSchema;
    /**
     * Date
     */
    date: string;
    /**
     * Hebrew Date
     */
    hebrew_date: string;
    /**
     * Calendars
     */
    calendars: Array<CalendarType>;
    /**
     * Years
     */
    years: number;
    /**
     * Days Until
     */
    days_until: number;
};

/**
 * UpcomingSpecialDatesSchema
 */
export type UpcomingSpecialDatesSchema = {
    /**
     * Today
     */
    today: string;
    /**
     * Today Hebrew Date
     */
    today_hebrew_date: string;
    /**
     * Days
     */
    days: number;
    /**
     * Occurrences
     */
    occurrences: Array<SpecialDateOccurrenceSchema>;
};

/**
 * ConvertSpecialDateQuerySchema
 */
export type ConvertSpecialDateQuerySchema = {
    calendar: CalendarType;
    /**
     * After Sunset
     */
    after_sunset?: boolean;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Hebrew Year
     */
    hebrew_year?: number | null;
    /**
     * Hebrew Month
     */
    hebrew_month?: number | null;
    /**
     * Hebrew Day
     */
    hebrew_day?: number | null;
};

/**
 * ConvertedDateSchema
 */
export type ConvertedDateSchema = {
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset: boolean;
    /**
     * Hebrew Year
     */
    hebrew_year: number;
    /**
     * Hebrew Month
     */
    hebrew_month: number;
    /**
     * Hebrew Day
     */
    hebrew_day: number;
    /**
     * Hebrew Date
     */
    hebrew_date: string;
};

/**
 * HebrewYearQuerySchema
 */
export type HebrewYearQuerySchema = {
    /**
     * Year
     */
    year: number;
};

/**
 * HebrewMonthOptionSchema
 */
export type HebrewMonthOptionSchema = {
    /**
     * Value
     */
    value: number;
    /**
     * Label
     */
    label: string;
    /**
     * Days
     */
    days: number;
};

/**
 * HebrewOptionSchema
 */
export type HebrewOptionSchema = {
    /**
     * Value
     */
    value: number;
    /**
     * Label
     */
    label: string;
};

/**
 * HebrewYearSchema
 */
export type HebrewYearSchema = {
    /**
     * Year
     */
    year: number;
    /**
     * Is Leap
     */
    is_leap: boolean;
    /**
     * Months
     */
    months: Array<HebrewMonthOptionSchema>;
    /**
     * Days
     */
    days: Array<HebrewOptionSchema>;
    /**
     * Years
     */
    years: Array<HebrewOptionSchema>;
};

/**
 * SpecialDateCalendarSchema
 */
export type SpecialDateCalendarSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Name
     */
    owner_name: string;
    /**
     * Is Owner
     */
    is_owner: boolean;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Event Count
     */
    event_count: number;
    /**
     * Max Event Count
     */
    max_event_count: number;
    /**
     * Hide From Upcoming
     */
    hide_from_upcoming: boolean;
    /**
     * Join Token
     */
    join_token: string | null;
};

/**
 * SpecialDateCalendarsSchema
 */
export type SpecialDateCalendarsSchema = {
    /**
     * Calendars
     */
    calendars: Array<SpecialDateCalendarSchema>;
};

/**
 * CreateSpecialDateCalendarSchema
 */
export type CreateSpecialDateCalendarSchema = {
    /**
     * Name
     */
    name: string;
};

/**
 * JoinSpecialDateCalendarSchema
 */
export type JoinSpecialDateCalendarSchema = {
    /**
     * Token
     */
    token: string;
};

/**
 * RenameSpecialDateCalendarSchema
 */
export type RenameSpecialDateCalendarSchema = {
    /**
     * Name
     */
    name: string;
};

/**
 * ShareSpecialDateCalendarSchema
 */
export type ShareSpecialDateCalendarSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * RemoveSpecialDateCalendarMemberSchema
 */
export type RemoveSpecialDateCalendarMemberSchema = {
    /**
     * User Id
     */
    user_id: number;
};

/**
 * SpecialDateCalendarPreferencesSchema
 */
export type SpecialDateCalendarPreferencesSchema = {
    /**
     * Hide From Upcoming
     */
    hide_from_upcoming: boolean;
};

/**
 * PendingInvitationSchema
 */
export type PendingInvitationSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SpecialDateCalendarMemberSchema
 */
export type SpecialDateCalendarMemberSchema = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    role: SpecialDateCalendarRole;
    /**
     * Is Me
     */
    is_me: boolean;
};

/**
 * SpecialDateCalendarMembersSchema
 */
export type SpecialDateCalendarMembersSchema = {
    /**
     * Members
     */
    members: Array<SpecialDateCalendarMemberSchema>;
    /**
     * Pending Invitations
     */
    pending_invitations: Array<PendingInvitationSchema>;
};

/**
 * SpecialDateCalendarRole
 */
export type SpecialDateCalendarRole = 'owner' | 'editor';

export type PaginateSpecialDatesViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Search
         */
        search?: string | null;
        category?: SpecialDateCategory | null;
        /**
         * Calendar Id
         */
        calendar_id?: number | null;
    };
    url: '/api/special-dates/dates/';
};

export type PaginateSpecialDatesViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputSpecialDateSchema;
};

export type PaginateSpecialDatesViewResponse = PaginateSpecialDatesViewResponses[keyof PaginateSpecialDatesViewResponses];

export type CreateSpecialDateViewData = {
    body: CreateSpecialDateSchema;
    path?: never;
    query?: never;
    url: '/api/special-dates/dates/';
};

export type CreateSpecialDateViewResponses = {
    /**
     * OK
     */
    200: SpecialDateSchema;
};

export type CreateSpecialDateViewResponse = CreateSpecialDateViewResponses[keyof CreateSpecialDateViewResponses];

export type MoveSpecialDatesViewData = {
    body: MoveSpecialDatesSchema;
    path?: never;
    query?: never;
    url: '/api/special-dates/dates/move/';
};

export type MoveSpecialDatesViewResponses = {
    /**
     * OK
     */
    200: EmptySchema;
};

export type MoveSpecialDatesViewResponse = MoveSpecialDatesViewResponses[keyof MoveSpecialDatesViewResponses];

export type DeleteSpecialDateViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/dates/{object_id}/';
};

export type DeleteSpecialDateViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateSpecialDateViewData = {
    body: UpdateSpecialDateSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/dates/{object_id}/';
};

export type UpdateSpecialDateViewResponses = {
    /**
     * OK
     */
    200: SpecialDateSchema;
};

export type UpdateSpecialDateViewResponse = UpdateSpecialDateViewResponses[keyof UpdateSpecialDateViewResponses];

export type GetUpcomingSpecialDatesViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/special-dates/upcoming/';
};

export type GetUpcomingSpecialDatesViewResponses = {
    /**
     * OK
     */
    200: UpcomingSpecialDatesSchema;
};

export type GetUpcomingSpecialDatesViewResponse = GetUpcomingSpecialDatesViewResponses[keyof GetUpcomingSpecialDatesViewResponses];

export type ConvertSpecialDateViewData = {
    body?: never;
    path?: never;
    query: {
        /**
         * CalendarType
         */
        calendar: 'gregorian' | 'hebrew';
        /**
         * After Sunset
         */
        after_sunset?: boolean;
        /**
         * Date
         */
        date?: string | null;
        /**
         * Hebrew Year
         */
        hebrew_year?: number | null;
        /**
         * Hebrew Month
         */
        hebrew_month?: number | null;
        /**
         * Hebrew Day
         */
        hebrew_day?: number | null;
    };
    url: '/api/special-dates/convert/';
};

export type ConvertSpecialDateViewResponses = {
    /**
     * OK
     */
    200: ConvertedDateSchema;
};

export type ConvertSpecialDateViewResponse = ConvertSpecialDateViewResponses[keyof ConvertSpecialDateViewResponses];

export type GetHebrewYearViewData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Year
         */
        year: number;
    };
    url: '/api/special-dates/hebrew-year/';
};

export type GetHebrewYearViewResponses = {
    /**
     * OK
     */
    200: HebrewYearSchema;
};

export type GetHebrewYearViewResponse = GetHebrewYearViewResponses[keyof GetHebrewYearViewResponses];

export type ListSpecialDateCalendarsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/special-dates/calendars/';
};

export type ListSpecialDateCalendarsViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarsSchema;
};

export type ListSpecialDateCalendarsViewResponse = ListSpecialDateCalendarsViewResponses[keyof ListSpecialDateCalendarsViewResponses];

export type CreateSpecialDateCalendarViewData = {
    body: CreateSpecialDateCalendarSchema;
    path?: never;
    query?: never;
    url: '/api/special-dates/calendars/';
};

export type CreateSpecialDateCalendarViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type CreateSpecialDateCalendarViewResponse = CreateSpecialDateCalendarViewResponses[keyof CreateSpecialDateCalendarViewResponses];

export type JoinSpecialDateCalendarViewData = {
    body: JoinSpecialDateCalendarSchema;
    path?: never;
    query?: never;
    url: '/api/special-dates/calendars/join/';
};

export type JoinSpecialDateCalendarViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type JoinSpecialDateCalendarViewResponse = JoinSpecialDateCalendarViewResponses[keyof JoinSpecialDateCalendarViewResponses];

export type DeleteSpecialDateCalendarViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/';
};

export type DeleteSpecialDateCalendarViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RenameSpecialDateCalendarViewData = {
    body: RenameSpecialDateCalendarSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/rename/';
};

export type RenameSpecialDateCalendarViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type RenameSpecialDateCalendarViewResponse = RenameSpecialDateCalendarViewResponses[keyof RenameSpecialDateCalendarViewResponses];

export type ShareSpecialDateCalendarViewData = {
    body: ShareSpecialDateCalendarSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/share/';
};

export type ShareSpecialDateCalendarViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type ShareSpecialDateCalendarViewResponse = ShareSpecialDateCalendarViewResponses[keyof ShareSpecialDateCalendarViewResponses];

export type RemoveSpecialDateCalendarMemberViewData = {
    body: RemoveSpecialDateCalendarMemberSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/remove-member/';
};

export type RemoveSpecialDateCalendarMemberViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type RemoveSpecialDateCalendarMemberViewResponse = RemoveSpecialDateCalendarMemberViewResponses[keyof RemoveSpecialDateCalendarMemberViewResponses];

export type LeaveSpecialDateCalendarViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/leave/';
};

export type LeaveSpecialDateCalendarViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type LeaveSpecialDateCalendarViewResponse = LeaveSpecialDateCalendarViewResponses[keyof LeaveSpecialDateCalendarViewResponses];

export type ResetSpecialDateCalendarLinkViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/reset-link/';
};

export type ResetSpecialDateCalendarLinkViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type ResetSpecialDateCalendarLinkViewResponse = ResetSpecialDateCalendarLinkViewResponses[keyof ResetSpecialDateCalendarLinkViewResponses];

export type UpdateSpecialDateCalendarPreferencesViewData = {
    body: SpecialDateCalendarPreferencesSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/preferences/';
};

export type UpdateSpecialDateCalendarPreferencesViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarSchema;
};

export type UpdateSpecialDateCalendarPreferencesViewResponse = UpdateSpecialDateCalendarPreferencesViewResponses[keyof UpdateSpecialDateCalendarPreferencesViewResponses];

export type ListSpecialDateCalendarMembersViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/calendars/{object_id}/members/';
};

export type ListSpecialDateCalendarMembersViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarMembersSchema;
};

export type ListSpecialDateCalendarMembersViewResponse = ListSpecialDateCalendarMembersViewResponses[keyof ListSpecialDateCalendarMembersViewResponses];
