// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateSpecialDatesFilterSchema
 */
export type PaginateSpecialDatesFilterSchema = {
    /**
     * Search
     */
    search?: string | null;
    category?: SpecialDateCategory | null;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * SpecialDateCategory
 */
export type SpecialDateCategory = 'birthday' | 'anniversary' | 'memorial' | 'other';

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * PaginationOutput[SpecialDateSchema]
 */
export type PaginationOutputSpecialDateSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<SpecialDateSchema>;
};

/**
 * SpecialDateRecurrence
 */
export type SpecialDateRecurrence = 'both' | 'gregorian' | 'hebrew';

/**
 * SpecialDateSchema
 */
export type SpecialDateSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset: boolean;
    category: SpecialDateCategory;
    recurrence: SpecialDateRecurrence;
    /**
     * Description
     */
    description: string;
    /**
     * Hebrew Date
     */
    hebrew_date: string;
    /**
     * Next Gregorian Date
     */
    next_gregorian_date: string;
    /**
     * Next Hebrew Date
     */
    next_hebrew_date: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateSpecialDateSchema
 */
export type CreateSpecialDateSchema = {
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset?: boolean;
    category: SpecialDateCategory;
    recurrence?: SpecialDateRecurrence;
    /**
     * Description
     */
    description: string;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateSpecialDateSchema
 */
export type UpdateSpecialDateSchema = {
    /**
     * Date
     */
    date?: string | null;
    /**
     * After Sunset
     */
    after_sunset?: boolean | null;
    category?: SpecialDateCategory | null;
    recurrence?: SpecialDateRecurrence | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CalendarType
 */
export type CalendarType = 'gregorian' | 'hebrew';

/**
 * SpecialDateOccurrenceSchema
 */
export type SpecialDateOccurrenceSchema = {
    special_date: SpecialDateSchema;
    /**
     * Date
     */
    date: string;
    /**
     * Hebrew Date
     */
    hebrew_date: string;
    /**
     * Calendars
     */
    calendars: Array<CalendarType>;
    /**
     * Years
     */
    years: number;
    /**
     * Days Until
     */
    days_until: number;
};

/**
 * UpcomingSpecialDatesSchema
 */
export type UpcomingSpecialDatesSchema = {
    /**
     * Today
     */
    today: string;
    /**
     * Today Hebrew Date
     */
    today_hebrew_date: string;
    /**
     * Days
     */
    days: number;
    /**
     * Occurrences
     */
    occurrences: Array<SpecialDateOccurrenceSchema>;
    /**
     * Total Count
     */
    total_count: number;
    /**
     * Max Count
     */
    max_count: number;
};

/**
 * HebrewDateQuerySchema
 */
export type HebrewDateQuerySchema = {
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset?: boolean;
};

/**
 * HebrewDateSchema
 */
export type HebrewDateSchema = {
    /**
     * Date
     */
    date: string;
    /**
     * After Sunset
     */
    after_sunset: boolean;
    /**
     * Hebrew Date
     */
    hebrew_date: string;
};

export type PaginateSpecialDatesViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Search
         */
        search?: string | null;
        category?: SpecialDateCategory | null;
    };
    url: '/api/special-dates/dates/';
};

export type PaginateSpecialDatesViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputSpecialDateSchema;
};

export type PaginateSpecialDatesViewResponse = PaginateSpecialDatesViewResponses[keyof PaginateSpecialDatesViewResponses];

export type CreateSpecialDateViewData = {
    body: CreateSpecialDateSchema;
    path?: never;
    query?: never;
    url: '/api/special-dates/dates/';
};

export type CreateSpecialDateViewResponses = {
    /**
     * OK
     */
    200: SpecialDateSchema;
};

export type CreateSpecialDateViewResponse = CreateSpecialDateViewResponses[keyof CreateSpecialDateViewResponses];

export type DeleteSpecialDateViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/dates/{object_id}/';
};

export type DeleteSpecialDateViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateSpecialDateViewData = {
    body: UpdateSpecialDateSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/special-dates/dates/{object_id}/';
};

export type UpdateSpecialDateViewResponses = {
    /**
     * OK
     */
    200: SpecialDateSchema;
};

export type UpdateSpecialDateViewResponse = UpdateSpecialDateViewResponses[keyof UpdateSpecialDateViewResponses];

export type GetUpcomingSpecialDatesViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/special-dates/upcoming/';
};

export type GetUpcomingSpecialDatesViewResponses = {
    /**
     * OK
     */
    200: UpcomingSpecialDatesSchema;
};

export type GetUpcomingSpecialDatesViewResponse = GetUpcomingSpecialDatesViewResponses[keyof GetUpcomingSpecialDatesViewResponses];

export type GetHebrewDateViewData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Date
         */
        date: string;
        /**
         * After Sunset
         */
        after_sunset?: boolean;
    };
    url: '/api/special-dates/hebrew-date/';
};

export type GetHebrewDateViewResponses = {
    /**
     * OK
     */
    200: HebrewDateSchema;
};

export type GetHebrewDateViewResponse = GetHebrewDateViewResponses[keyof GetHebrewDateViewResponses];
