// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateApartmentProspectViewData, CreateApartmentProspectViewResponses, CreateRentalProjectViewData, CreateRentalProjectViewResponses, DeleteApartmentImageViewData, DeleteApartmentImageViewResponses, DeleteApartmentProspectViewData, DeleteApartmentProspectViewResponses, DeleteRentalProjectViewData, DeleteRentalProjectViewResponses, FinishRentalProjectViewData, FinishRentalProjectViewResponses, GetApartmentProspectViewData, GetApartmentProspectViewResponses, GetRentalProjectViewData, GetRentalProjectViewResponses, ListProjectMembersViewData, ListProjectMembersViewResponses, PaginateApartmentProspectsViewData, PaginateApartmentProspectsViewResponses, PaginateRentalProjectsViewData, PaginateRentalProjectsViewResponses, ReopenRentalProjectViewData, ReopenRentalProjectViewResponses, ShareRentalProjectViewData, ShareRentalProjectViewResponses, UnshareRentalProjectViewData, UnshareRentalProjectViewResponses, UpdateApartmentProspectViewData, UpdateApartmentProspectViewResponses, UpdateRentalProjectViewData, UpdateRentalProjectViewResponses, UploadApartmentProspectImageViewData, UploadApartmentProspectImageViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateRentalProjectsView = <ThrowOnError extends boolean = false>(options?: Options<PaginateRentalProjectsViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateRentalProjectsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/',
    ...options
});

/**
 * Post
 */
export const createRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<CreateRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<CreateRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<DeleteRentalProjectViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteRentalProjectViewResponses, unknown, ThrowOnError>({
    url: '/api/apartment-hunt/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<GetRentalProjectViewData, ThrowOnError>) => (options.client ?? client).get<GetRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<UpdateRentalProjectViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const shareRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<ShareRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<ShareRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/share/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unshareRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<UnshareRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<UnshareRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/unshare/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const listProjectMembersView = <ThrowOnError extends boolean = false>(options: Options<ListProjectMembersViewData, ThrowOnError>) => (options.client ?? client).get<ListProjectMembersViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/members/',
    ...options
});

/**
 * Post
 */
export const finishRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<FinishRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<FinishRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/finish/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const reopenRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<ReopenRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<ReopenRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{object_id}/reopen/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pagination
 */
export const paginateApartmentProspectsView = <ThrowOnError extends boolean = false>(options: Options<PaginateApartmentProspectsViewData, ThrowOnError>) => (options.client ?? client).get<PaginateApartmentProspectsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/projects/{project_id}/prospects/',
    ...options
});

/**
 * Post
 */
export const createApartmentProspectView = <ThrowOnError extends boolean = false>(options: Options<CreateApartmentProspectViewData, ThrowOnError>) => (options.client ?? client).post<CreateApartmentProspectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/prospects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteApartmentProspectView = <ThrowOnError extends boolean = false>(options: Options<DeleteApartmentProspectViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteApartmentProspectViewResponses, unknown, ThrowOnError>({
    url: '/api/apartment-hunt/prospects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getApartmentProspectView = <ThrowOnError extends boolean = false>(options: Options<GetApartmentProspectViewData, ThrowOnError>) => (options.client ?? client).get<GetApartmentProspectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/prospects/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateApartmentProspectView = <ThrowOnError extends boolean = false>(options: Options<UpdateApartmentProspectViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateApartmentProspectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/apartment-hunt/prospects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const uploadApartmentProspectImageView = <ThrowOnError extends boolean = false>(options: Options<UploadApartmentProspectImageViewData, ThrowOnError>) => (options.client ?? client).post<UploadApartmentProspectImageViewResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/apartment-hunt/prospects/{object_id}/upload-image/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteApartmentImageView = <ThrowOnError extends boolean = false>(options: Options<DeleteApartmentImageViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteApartmentImageViewResponses, unknown, ThrowOnError>({
    url: '/api/apartment-hunt/images/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
