// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateRentalProjectsFilterSchema
 */
export type PaginateRentalProjectsFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * Currency
 */
export type Currency = 'nis' | 'usd' | 'eur' | 'gbp';

/**
 * PaginationOutput[RentalProjectSchema]
 */
export type PaginationOutputRentalProjectSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<RentalProjectSchema>;
};

/**
 * ProjectApp
 */
export type ProjectApp = 'apartment_hunt' | 'renters_crm' | 'villa_villekulla';

/**
 * ProjectStatus
 */
export type ProjectStatus = 'active' | 'finished';

/**
 * RentalProjectSchema
 */
export type RentalProjectSchema = {
    /**
     * Id
     */
    id: number;
    app: ProjectApp;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    currency: Currency;
    status: ProjectStatus;
    /**
     * Initial Asked Rent
     */
    initial_asked_rent: number | null;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Owner Username
     */
    owner_username: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateRentalProjectSchema
 */
export type CreateRentalProjectSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    currency?: Currency;
    /**
     * Initial Asked Rent
     */
    initial_asked_rent?: number | string | null;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateRentalProjectSchema
 */
export type UpdateRentalProjectSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    currency?: Currency | null;
    /**
     * Initial Asked Rent
     */
    initial_asked_rent?: number | string | null;
};

/**
 * ProjectRole
 */
export type ProjectRole = 'owner' | 'collaborator';

/**
 * ShareRentalProjectSchema
 */
export type ShareRentalProjectSchema = {
    /**
     * Identifier
     */
    identifier: string;
    role?: ProjectRole;
};

/**
 * UnshareRentalProjectSchema
 */
export type UnshareRentalProjectSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * PendingInvitationSchema
 */
export type PendingInvitationSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ProjectMembersSchema
 */
export type ProjectMembersSchema = {
    /**
     * Members
     */
    members: Array<ProjectMembershipSchema>;
    /**
     * Pending Invitations
     */
    pending_invitations: Array<PendingInvitationSchema>;
};

/**
 * ProjectMembershipSchema
 */
export type ProjectMembershipSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name: string;
    role: ProjectRole;
};

/**
 * PaginateApartmentProspectsFilterSchema
 */
export type PaginateApartmentProspectsFilterSchema = {
    /**
     * Status
     */
    status?: string | null;
};

/**
 * ProspectsByProjectPath
 */
export type ProspectsByProjectPath = {
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * ApartmentImageSchema
 */
export type ApartmentImageSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Caption
     */
    caption: string;
    /**
     * Order
     */
    order: number;
};

/**
 * ApartmentProspectSchema
 */
export type ApartmentProspectSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Title
     */
    title: string;
    status: ProspectStatus;
    /**
     * Town
     */
    town: string;
    /**
     * Full Address
     */
    full_address: string;
    /**
     * Monthly Rent
     */
    monthly_rent: number | null;
    /**
     * Via Agency
     */
    via_agency: boolean;
    /**
     * Agency Fee
     */
    agency_fee: number | null;
    /**
     * Monthly Tax Benefit
     */
    monthly_tax_benefit: number | null;
    /**
     * Has Protected Room
     */
    has_protected_room: boolean;
    /**
     * Liked Level
     */
    liked_level: number | null;
    /**
     * Rooms
     */
    rooms: number | null;
    /**
     * Floor
     */
    floor: number | null;
    /**
     * Size Sqm
     */
    size_sqm: number | null;
    /**
     * Available From
     */
    available_from: string | null;
    /**
     * Listing Url
     */
    listing_url: string;
    /**
     * Notes
     */
    notes: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Images
     */
    images: Array<ApartmentImageSchema>;
    /**
     * Contacts
     */
    contacts: Array<ProspectContactSchema>;
};

/**
 * ContactMethod
 */
export type ContactMethod = 'facebook' | 'whatsapp' | 'phone' | 'email' | 'agency' | 'other';

/**
 * PaginationOutput[ApartmentProspectSchema]
 */
export type PaginationOutputApartmentProspectSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ApartmentProspectSchema>;
};

/**
 * ProspectContactSchema
 */
export type ProspectContactSchema = {
    /**
     * Id
     */
    id: number;
    method: ContactMethod;
    /**
     * Value
     */
    value: string;
    /**
     * Label
     */
    label: string;
    /**
     * Order
     */
    order: number;
};

/**
 * ProspectStatus
 */
export type ProspectStatus = 'saw' | 'contacted' | 'waiting_for_invitation' | 'saw_waiting_for_them' | 'need_to_decide' | 'declined' | 'accepted' | 'signed';

/**
 * CreateApartmentProspectSchema
 */
export type CreateApartmentProspectSchema = {
    /**
     * Title
     */
    title?: string | null;
    status?: ProspectStatus | null;
    /**
     * Town
     */
    town?: string | null;
    /**
     * Full Address
     */
    full_address?: string | null;
    /**
     * Monthly Rent
     */
    monthly_rent?: number | string | null;
    /**
     * Via Agency
     */
    via_agency?: boolean | null;
    /**
     * Agency Fee
     */
    agency_fee?: number | string | null;
    /**
     * Monthly Tax Benefit
     */
    monthly_tax_benefit?: number | string | null;
    /**
     * Has Protected Room
     */
    has_protected_room?: boolean | null;
    /**
     * Liked Level
     */
    liked_level?: number | null;
    /**
     * Rooms
     */
    rooms?: number | string | null;
    /**
     * Floor
     */
    floor?: number | null;
    /**
     * Size Sqm
     */
    size_sqm?: number | null;
    /**
     * Available From
     */
    available_from?: string | null;
    /**
     * Listing Url
     */
    listing_url?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Contacts
     */
    contacts?: Array<ProspectContactInputSchema>;
};

/**
 * ProspectContactInputSchema
 */
export type ProspectContactInputSchema = {
    method?: ContactMethod;
    /**
     * Value
     */
    value?: string;
    /**
     * Label
     */
    label?: string;
    /**
     * Order
     */
    order?: number;
};

/**
 * UpdateApartmentProspectSchema
 */
export type UpdateApartmentProspectSchema = {
    /**
     * Title
     */
    title?: string | null;
    status?: ProspectStatus | null;
    /**
     * Town
     */
    town?: string | null;
    /**
     * Full Address
     */
    full_address?: string | null;
    /**
     * Monthly Rent
     */
    monthly_rent?: number | string | null;
    /**
     * Via Agency
     */
    via_agency?: boolean | null;
    /**
     * Agency Fee
     */
    agency_fee?: number | string | null;
    /**
     * Monthly Tax Benefit
     */
    monthly_tax_benefit?: number | string | null;
    /**
     * Has Protected Room
     */
    has_protected_room?: boolean | null;
    /**
     * Liked Level
     */
    liked_level?: number | null;
    /**
     * Rooms
     */
    rooms?: number | string | null;
    /**
     * Floor
     */
    floor?: number | null;
    /**
     * Size Sqm
     */
    size_sqm?: number | null;
    /**
     * Available From
     */
    available_from?: string | null;
    /**
     * Listing Url
     */
    listing_url?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<ProspectContactInputSchema> | null;
};

export type PaginateRentalProjectsViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/apartment-hunt/projects/';
};

export type PaginateRentalProjectsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputRentalProjectSchema;
};

export type PaginateRentalProjectsViewResponse = PaginateRentalProjectsViewResponses[keyof PaginateRentalProjectsViewResponses];

export type CreateRentalProjectViewData = {
    body: CreateRentalProjectSchema;
    path?: never;
    query?: never;
    url: '/api/apartment-hunt/projects/';
};

export type CreateRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type CreateRentalProjectViewResponse = CreateRentalProjectViewResponses[keyof CreateRentalProjectViewResponses];

export type DeleteRentalProjectViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/';
};

export type DeleteRentalProjectViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRentalProjectViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/';
};

export type GetRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type GetRentalProjectViewResponse = GetRentalProjectViewResponses[keyof GetRentalProjectViewResponses];

export type UpdateRentalProjectViewData = {
    body: UpdateRentalProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/';
};

export type UpdateRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type UpdateRentalProjectViewResponse = UpdateRentalProjectViewResponses[keyof UpdateRentalProjectViewResponses];

export type ShareRentalProjectViewData = {
    body: ShareRentalProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/share/';
};

export type ShareRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type ShareRentalProjectViewResponse = ShareRentalProjectViewResponses[keyof ShareRentalProjectViewResponses];

export type UnshareRentalProjectViewData = {
    body: UnshareRentalProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/unshare/';
};

export type UnshareRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type UnshareRentalProjectViewResponse = UnshareRentalProjectViewResponses[keyof UnshareRentalProjectViewResponses];

export type ListProjectMembersViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/members/';
};

export type ListProjectMembersViewResponses = {
    /**
     * OK
     */
    200: ProjectMembersSchema;
};

export type ListProjectMembersViewResponse = ListProjectMembersViewResponses[keyof ListProjectMembersViewResponses];

export type FinishRentalProjectViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/finish/';
};

export type FinishRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type FinishRentalProjectViewResponse = FinishRentalProjectViewResponses[keyof FinishRentalProjectViewResponses];

export type ReopenRentalProjectViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/projects/{object_id}/reopen/';
};

export type ReopenRentalProjectViewResponses = {
    /**
     * OK
     */
    200: RentalProjectSchema;
};

export type ReopenRentalProjectViewResponse = ReopenRentalProjectViewResponses[keyof ReopenRentalProjectViewResponses];

export type PaginateApartmentProspectsViewData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/apartment-hunt/projects/{project_id}/prospects/';
};

export type PaginateApartmentProspectsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputApartmentProspectSchema;
};

export type PaginateApartmentProspectsViewResponse = PaginateApartmentProspectsViewResponses[keyof PaginateApartmentProspectsViewResponses];

export type CreateApartmentProspectViewData = {
    body: CreateApartmentProspectSchema;
    path?: never;
    query?: never;
    url: '/api/apartment-hunt/prospects/';
};

export type CreateApartmentProspectViewResponses = {
    /**
     * OK
     */
    200: ApartmentProspectSchema;
};

export type CreateApartmentProspectViewResponse = CreateApartmentProspectViewResponses[keyof CreateApartmentProspectViewResponses];

export type DeleteApartmentProspectViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/prospects/{object_id}/';
};

export type DeleteApartmentProspectViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApartmentProspectViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/prospects/{object_id}/';
};

export type GetApartmentProspectViewResponses = {
    /**
     * OK
     */
    200: ApartmentProspectSchema;
};

export type GetApartmentProspectViewResponse = GetApartmentProspectViewResponses[keyof GetApartmentProspectViewResponses];

export type UpdateApartmentProspectViewData = {
    body: UpdateApartmentProspectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/prospects/{object_id}/';
};

export type UpdateApartmentProspectViewResponses = {
    /**
     * OK
     */
    200: ApartmentProspectSchema;
};

export type UpdateApartmentProspectViewResponse = UpdateApartmentProspectViewResponses[keyof UpdateApartmentProspectViewResponses];

export type UploadApartmentProspectImageViewData = {
    /**
     * FileParams
     */
    body: {
        /**
         * Files
         */
        files: Array<Blob | File>;
    };
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/prospects/{object_id}/upload-image/';
};

export type UploadApartmentProspectImageViewResponses = {
    /**
     * OK
     */
    200: ApartmentProspectSchema;
};

export type UploadApartmentProspectImageViewResponse = UploadApartmentProspectImageViewResponses[keyof UploadApartmentProspectImageViewResponses];

export type DeleteApartmentImageViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/apartment-hunt/images/{object_id}/';
};

export type DeleteApartmentImageViewResponses = {
    /**
     * OK
     */
    200: unknown;
};
