# Generated by Django 5.2.9 on 2026-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_repeating',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
