# Generated by Django 5.2.9 on 2026-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_task_is_repeating_task_last_reset_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
