// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateDreamDiaryEntryViewData, CreateDreamDiaryEntryViewResponses, DeleteDreamDiaryEntryViewData, DeleteDreamDiaryEntryViewResponses, GetDreamDiaryCalendarViewData, GetDreamDiaryCalendarViewResponses, PaginateDreamDiaryEntriesViewData, PaginateDreamDiaryEntriesViewResponses, UpdateDreamDiaryEntryViewData, UpdateDreamDiaryEntryViewResponses, UploadDreamDiaryEntryImageViewData, UploadDreamDiaryEntryImageViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateDreamDiaryEntriesView = <ThrowOnError extends boolean = false>(options?: Options<PaginateDreamDiaryEntriesViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateDreamDiaryEntriesViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dream-diary/',
    ...options
});

/**
 * Post
 */
export const createDreamDiaryEntryView = <ThrowOnError extends boolean = false>(options: Options<CreateDreamDiaryEntryViewData, ThrowOnError>) => (options.client ?? client).post<CreateDreamDiaryEntryViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dream-diary/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteDreamDiaryEntryView = <ThrowOnError extends boolean = false>(options: Options<DeleteDreamDiaryEntryViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteDreamDiaryEntryViewResponses, unknown, ThrowOnError>({
    url: '/api/dream-diary/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Patch
 */
export const updateDreamDiaryEntryView = <ThrowOnError extends boolean = false>(options: Options<UpdateDreamDiaryEntryViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateDreamDiaryEntryViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dream-diary/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const uploadDreamDiaryEntryImageView = <ThrowOnError extends boolean = false>(options: Options<UploadDreamDiaryEntryImageViewData, ThrowOnError>) => (options.client ?? client).post<UploadDreamDiaryEntryImageViewResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/dream-diary/{object_id}/upload-image/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get
 */
export const getDreamDiaryCalendarView = <ThrowOnError extends boolean = false>(options?: Options<GetDreamDiaryCalendarViewData, ThrowOnError>) => (options?.client ?? client).get<GetDreamDiaryCalendarViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/dream-diary/calendar/',
    ...options
});
