// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateDreamDiaryEntriesFilterSchema
 */
export type PaginateDreamDiaryEntriesFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * DreamDiaryEntrySchema
 */
export type DreamDiaryEntrySchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
    /**
     * Time
     */
    time: string;
    /**
     * Image Url
     */
    image_url: string | null;
};

/**
 * PaginationOutput[DreamDiaryEntrySchema]
 */
export type PaginationOutputDreamDiaryEntrySchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<DreamDiaryEntrySchema>;
};

/**
 * CreateDreamDiaryEntrySchema
 */
export type CreateDreamDiaryEntrySchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Time
     */
    time: string;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateDreamDiaryEntrySchema
 */
export type UpdateDreamDiaryEntrySchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Time
     */
    time?: string | null;
};

/**
 * DreamDiaryCalendarSchema
 */
export type DreamDiaryCalendarSchema = {
    /**
     * Logged Dates
     */
    logged_dates: Array<string>;
};

export type PaginateDreamDiaryEntriesViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/dream-diary/';
};

export type PaginateDreamDiaryEntriesViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputDreamDiaryEntrySchema;
};

export type PaginateDreamDiaryEntriesViewResponse = PaginateDreamDiaryEntriesViewResponses[keyof PaginateDreamDiaryEntriesViewResponses];

export type CreateDreamDiaryEntryViewData = {
    body: CreateDreamDiaryEntrySchema;
    path?: never;
    query?: never;
    url: '/api/dream-diary/';
};

export type CreateDreamDiaryEntryViewResponses = {
    /**
     * OK
     */
    200: DreamDiaryEntrySchema;
};

export type CreateDreamDiaryEntryViewResponse = CreateDreamDiaryEntryViewResponses[keyof CreateDreamDiaryEntryViewResponses];

export type DeleteDreamDiaryEntryViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/dream-diary/{object_id}/';
};

export type DeleteDreamDiaryEntryViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateDreamDiaryEntryViewData = {
    body: UpdateDreamDiaryEntrySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/dream-diary/{object_id}/';
};

export type UpdateDreamDiaryEntryViewResponses = {
    /**
     * OK
     */
    200: DreamDiaryEntrySchema;
};

export type UpdateDreamDiaryEntryViewResponse = UpdateDreamDiaryEntryViewResponses[keyof UpdateDreamDiaryEntryViewResponses];

export type UploadDreamDiaryEntryImageViewData = {
    /**
     * FileParams
     */
    body: {
        /**
         * Files
         */
        files: Array<Blob | File>;
    };
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/dream-diary/{object_id}/upload-image/';
};

export type UploadDreamDiaryEntryImageViewResponses = {
    /**
     * OK
     */
    200: DreamDiaryEntrySchema;
};

export type UploadDreamDiaryEntryImageViewResponse = UploadDreamDiaryEntryImageViewResponses[keyof UploadDreamDiaryEntryImageViewResponses];

export type GetDreamDiaryCalendarViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dream-diary/calendar/';
};

export type GetDreamDiaryCalendarViewResponses = {
    /**
     * OK
     */
    200: DreamDiaryCalendarSchema;
};

export type GetDreamDiaryCalendarViewResponse = GetDreamDiaryCalendarViewResponses[keyof GetDreamDiaryCalendarViewResponses];
