// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGenresViewData, GetGenresViewResponses, GetRandomTrackViewData, GetRandomTrackViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const getRandomTrackView = <ThrowOnError extends boolean = false>(options?: Options<GetRandomTrackViewData, ThrowOnError>) => (options?.client ?? client).get<GetRandomTrackViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/genre-trainer/random-track/',
    ...options
});

/**
 * Get
 */
export const getGenresView = <ThrowOnError extends boolean = false>(options?: Options<GetGenresViewData, ThrowOnError>) => (options?.client ?? client).get<GetGenresViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/genre-trainer/genres/',
    ...options
});
