// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetGenresViewData, GetGenresViewResponses, GetRandomTrackViewData, GetRandomTrackViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    client?: Client;
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const getRandomTrackView = <ThrowOnError extends boolean = false>(options?: Options<GetRandomTrackViewData, ThrowOnError>) => (options?.client ?? client).get<GetRandomTrackViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/genre-trainer/random-track/',
    ...options
});

/**
 * Get
 */
export const getGenresView = <ThrowOnError extends boolean = false>(options?: Options<GetGenresViewData, ThrowOnError>) => (options?.client ?? client).get<GetGenresViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/genre-trainer/genres/',
    ...options
});
