// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LayerPatternSchema = {
    subdivision: string;
    steps: Array<string | null>;
    velocities?: Array<number | null> | null;
};

export type InstrumentConfigSchema = {
    type: string;
    options: Record<string, unknown>;
};

export type EffectConfigSchema = {
    type: string;
    options: Record<string, unknown>;
    wet: number;
};

export type AutomationSpecSchema = {
    target: string;
    from_val: number;
    to_val: number;
    waveform?: string;
};

export type TrackLayerSchema = {
    id: string;
    role: string;
    volume: number;
    note_duration: string;
    instrument: InstrumentConfigSchema;
    effects: Array<EffectConfigSchema>;
    pattern: LayerPatternSchema;
    entry_loop?: number;
    dropout_prob?: number;
    automation?: Array<AutomationSpecSchema>;
};

export type TrackSchema = {
    id: string;
    genre: string;
    bpm: number;
    layers: Array<TrackLayerSchema>;
};

export type GetRandomTrackOutput = {
    track: TrackSchema;
};

export type GetGenresOutput = {
    genres: Array<string>;
};

export type GetRandomTrackViewData = {
    body?: never;
    path?: never;
    query?: { genres?: string };
    url: '/api/genre-trainer/random-track/';
};

export type GetRandomTrackViewResponses = {
    200: GetRandomTrackOutput;
};

export type GetRandomTrackViewResponse = GetRandomTrackViewResponses[keyof GetRandomTrackViewResponses];

export type GetGenresViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/genre-trainer/genres/';
};

export type GetGenresViewResponses = {
    200: GetGenresOutput;
};

export type GetGenresViewResponse = GetGenresViewResponses[keyof GetGenresViewResponses];
