// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * GetRandomTrackQuerySchema
 */
export type GetRandomTrackQuerySchema = {
    /**
     * Genres
     */
    genres?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * AutomationSpecSchema
 */
export type AutomationSpecSchema = {
    /**
     * Target
     */
    target: string;
    /**
     * From Val
     */
    from_val: number;
    /**
     * To Val
     */
    to_val: number;
    /**
     * Waveform
     */
    waveform?: string;
};

/**
 * EffectConfigSchema
 */
export type EffectConfigSchema = {
    /**
     * Type
     */
    type: string;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Wet
     */
    wet?: number;
};

/**
 * GetRandomTrackOutput
 */
export type GetRandomTrackOutput = {
    track: TrackSchema;
};

/**
 * InstrumentConfigSchema
 */
export type InstrumentConfigSchema = {
    /**
     * Type
     */
    type: string;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
};

/**
 * LayerPatternSchema
 */
export type LayerPatternSchema = {
    /**
     * Subdivision
     */
    subdivision: string;
    /**
     * Steps
     */
    steps: Array<string | null>;
    /**
     * Velocities
     */
    velocities?: Array<number | null> | null;
};

/**
 * TrackLayerSchema
 */
export type TrackLayerSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Volume
     */
    volume: number;
    /**
     * Note Duration
     */
    note_duration?: string;
    instrument: InstrumentConfigSchema;
    /**
     * Effects
     */
    effects: Array<EffectConfigSchema>;
    pattern: LayerPatternSchema;
    /**
     * Entry Loop
     */
    entry_loop?: number;
    /**
     * Dropout Prob
     */
    dropout_prob?: number;
    /**
     * Automation
     */
    automation?: Array<AutomationSpecSchema>;
    /**
     * Loop Modulo
     */
    loop_modulo?: number;
    /**
     * Loop Modulo Remainder
     */
    loop_modulo_remainder?: number;
    /**
     * Pan
     */
    pan?: number | null;
};

/**
 * TrackSchema
 */
export type TrackSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Genre
     */
    genre: string;
    /**
     * Bpm
     */
    bpm: number;
    /**
     * Swing
     */
    swing?: number;
    /**
     * Layers
     */
    layers: Array<TrackLayerSchema>;
};

/**
 * GetGenresOutput
 */
export type GetGenresOutput = {
    /**
     * Genres
     */
    genres: Array<string>;
};

export type GetRandomTrackViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Genres
         */
        genres?: string | null;
    };
    url: '/api/genre-trainer/random-track/';
};

export type GetRandomTrackViewResponses = {
    /**
     * OK
     */
    200: GetRandomTrackOutput;
};

export type GetRandomTrackViewResponse = GetRandomTrackViewResponses[keyof GetRandomTrackViewResponses];

export type GetGenresViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/genre-trainer/genres/';
};

export type GetGenresViewResponses = {
    /**
     * OK
     */
    200: GetGenresOutput;
};

export type GetGenresViewResponse = GetGenresViewResponses[keyof GetGenresViewResponses];
