// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApproveNodeViewData, ApproveNodeViewResponses, GenerateContentViewData, GenerateContentViewResponses, GetRandomNodesViewData, GetRandomNodesViewResponses, GetReviewQueueViewData, GetReviewQueueViewResponses, IngestNodeViewData, IngestNodeViewResponses, ReadNodeViewData, ReadNodeViewResponses, UpdateNodeTitleViewData, UpdateNodeTitleViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const readNodeView = <ThrowOnError extends boolean = false>(options: Options<ReadNodeViewData, ThrowOnError>) => (options.client ?? client).get<ReadNodeViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/{object_id}/',
    ...options
});

/**
 * Get
 */
export const getRandomNodesView = <ThrowOnError extends boolean = false>(options?: Options<GetRandomNodesViewData, ThrowOnError>) => (options?.client ?? client).get<GetRandomNodesViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/random/',
    ...options
});

/**
 * Get
 */
export const getReviewQueueView = <ThrowOnError extends boolean = false>(options?: Options<GetReviewQueueViewData, ThrowOnError>) => (options?.client ?? client).get<GetReviewQueueViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/review-queue/',
    ...options
});

/**
 * Post
 */
export const ingestNodeView = <ThrowOnError extends boolean = false>(options: Options<IngestNodeViewData, ThrowOnError>) => (options.client ?? client).post<IngestNodeViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/ingest/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const generateContentView = <ThrowOnError extends boolean = false>(options: Options<GenerateContentViewData, ThrowOnError>) => (options.client ?? client).post<GenerateContentViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/{object_id}/generate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const approveNodeView = <ThrowOnError extends boolean = false>(options: Options<ApproveNodeViewData, ThrowOnError>) => (options.client ?? client).post<ApproveNodeViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/{object_id}/approve/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const updateNodeTitleView = <ThrowOnError extends boolean = false>(options: Options<UpdateNodeTitleViewData, ThrowOnError>) => (options.client ?? client).post<UpdateNodeTitleViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/japanese/{object_id}/update-title/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
