// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * EdgeType
 */
export type EdgeType = 'contains' | 'composed_of' | 'uses_rule' | 'example_of' | 'exception_to' | 'synonym_of' | 'related_to' | 'same_kanji_as';

/**
 * IncomingEdgeSchema
 */
export type IncomingEdgeSchema = {
    /**
     * Id
     */
    id: number;
    edge_type: EdgeType;
    /**
     * Edge Metadata
     */
    edge_metadata: {
        [key: string]: unknown;
    };
    from_node: NodeSummarySchema;
};

/**
 * JlptLevel
 */
export type JlptLevel = 'n5' | 'n4' | 'n3' | 'n2' | 'n1';

/**
 * KanjiSchema
 */
export type KanjiSchema = {
    /**
     * Character
     */
    character: string;
    /**
     * Readings On
     */
    readings_on?: Array<string>;
    /**
     * Readings Kun
     */
    readings_kun?: Array<string>;
    /**
     * Meanings
     */
    meanings?: Array<string>;
    /**
     * Radicals
     */
    radicals?: Array<string>;
};

/**
 * NodeDetailSchema
 */
export type NodeDetailSchema = {
    /**
     * Id
     */
    id: number;
    type: NodeType;
    status: NodeStatus;
    /**
     * Canonical Key
     */
    canonical_key: string;
    jlpt_level: JlptLevel | null;
    sentence_data: SentenceSchema | null;
    word_data: WordSchema | null;
    kanji_data: KanjiSchema | null;
    particle_data: ParticleSchema | null;
    rule_data: RuleSchema | null;
    /**
     * Content Html
     */
    content_html: string;
    /**
     * Notes
     */
    notes: string;
    /**
     * Outgoing Edges
     */
    outgoing_edges: Array<OutgoingEdgeSchema>;
    /**
     * Incoming Edges
     */
    incoming_edges: Array<IncomingEdgeSchema>;
};

/**
 * NodeStatus
 */
export type NodeStatus = 'stub' | 'generating' | 'needs_review' | 'published';

/**
 * NodeSummarySchema
 */
export type NodeSummarySchema = {
    /**
     * Id
     */
    id: number;
    type: NodeType;
    status: NodeStatus;
    /**
     * Canonical Key
     */
    canonical_key: string;
    jlpt_level: JlptLevel | null;
    sentence_data: SentenceSchema | null;
    word_data: WordSchema | null;
    kanji_data: KanjiSchema | null;
    particle_data: ParticleSchema | null;
    rule_data: RuleSchema | null;
};

/**
 * NodeType
 */
export type NodeType = 'sentence' | 'word' | 'kanji' | 'particle' | 'rule';

/**
 * OutgoingEdgeSchema
 */
export type OutgoingEdgeSchema = {
    /**
     * Id
     */
    id: number;
    edge_type: EdgeType;
    /**
     * Edge Metadata
     */
    edge_metadata: {
        [key: string]: unknown;
    };
    to_node: NodeSummarySchema;
};

/**
 * ParticleSchema
 */
export type ParticleSchema = {
    /**
     * Particle
     */
    particle: string;
    /**
     * Primary Function
     */
    primary_function?: string;
};

/**
 * RuleCategory
 */
export type RuleCategory = 'conjugation' | 'sentence_structure' | 'politeness' | 'particle_usage' | 'counters' | 'expression_pattern' | 'other';

/**
 * RuleSchema
 */
export type RuleSchema = {
    /**
     * Name
     */
    name: string;
    category?: RuleCategory;
};

/**
 * SentenceSchema
 */
export type SentenceSchema = {
    /**
     * Japanese
     */
    japanese: string;
    /**
     * English Translation
     */
    english_translation: string;
};

/**
 * WordSchema
 */
export type WordSchema = {
    /**
     * Base Form
     */
    base_form: string;
    /**
     * Reading
     */
    reading: string;
    word_type: WordType;
    word_sub_type?: WordSubType | null;
    /**
     * Meanings
     */
    meanings?: Array<string>;
};

/**
 * WordSubType
 */
export type WordSubType = 'godan' | 'ichidan' | 'irregular_verb' | 'i_adjective' | 'na_adjective';

/**
 * WordType
 */
export type WordType = 'verb' | 'noun' | 'adjective' | 'adverb' | 'expression' | 'counter' | 'pronoun' | 'interjection' | 'conjunction';

/**
 * GetRandomNodesQuery
 */
export type GetRandomNodesQuery = {
    /**
     * Types
     */
    types?: string;
    /**
     * Count
     */
    count?: number;
};

/**
 * GetRandomNodesResponseSchema
 */
export type GetRandomNodesResponseSchema = {
    /**
     * Nodes
     */
    nodes: Array<NodeSummarySchema>;
};

/**
 * GetReviewQueueResponseSchema
 */
export type GetReviewQueueResponseSchema = {
    /**
     * Stubs
     */
    stubs: Array<NodeSummarySchema>;
    /**
     * Needs Review
     */
    needs_review: Array<NodeSummarySchema>;
};

/**
 * IngestNodeSchema
 */
export type IngestNodeSchema = {
    /**
     * Text
     */
    text: string;
};

/**
 * GenerateContentInputSchema
 */
export type GenerateContentInputSchema = {
    /**
     * User Note
     */
    user_note?: string | null;
};

/**
 * UpdateNodeTitleInputSchema
 */
export type UpdateNodeTitleInputSchema = {
    /**
     * Title
     */
    title: string;
};

export type ReadNodeViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/japanese/{object_id}/';
};

export type ReadNodeViewResponses = {
    /**
     * OK
     */
    200: NodeDetailSchema;
};

export type ReadNodeViewResponse = ReadNodeViewResponses[keyof ReadNodeViewResponses];

export type GetRandomNodesViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Types
         */
        types?: string;
        /**
         * Count
         */
        count?: number;
    };
    url: '/api/japanese/random/';
};

export type GetRandomNodesViewResponses = {
    /**
     * OK
     */
    200: GetRandomNodesResponseSchema;
};

export type GetRandomNodesViewResponse = GetRandomNodesViewResponses[keyof GetRandomNodesViewResponses];

export type GetReviewQueueViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/japanese/review-queue/';
};

export type GetReviewQueueViewResponses = {
    /**
     * OK
     */
    200: GetReviewQueueResponseSchema;
};

export type GetReviewQueueViewResponse = GetReviewQueueViewResponses[keyof GetReviewQueueViewResponses];

export type IngestNodeViewData = {
    body: IngestNodeSchema;
    path?: never;
    query?: never;
    url: '/api/japanese/ingest/';
};

export type IngestNodeViewResponses = {
    /**
     * OK
     */
    200: NodeDetailSchema;
};

export type IngestNodeViewResponse = IngestNodeViewResponses[keyof IngestNodeViewResponses];

export type GenerateContentViewData = {
    body: GenerateContentInputSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/japanese/{object_id}/generate/';
};

export type GenerateContentViewResponses = {
    /**
     * OK
     */
    200: NodeDetailSchema;
};

export type GenerateContentViewResponse = GenerateContentViewResponses[keyof GenerateContentViewResponses];

export type ApproveNodeViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/japanese/{object_id}/approve/';
};

export type ApproveNodeViewResponses = {
    /**
     * OK
     */
    200: NodeDetailSchema;
};

export type ApproveNodeViewResponse = ApproveNodeViewResponses[keyof ApproveNodeViewResponses];

export type UpdateNodeTitleViewData = {
    body: UpdateNodeTitleInputSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/japanese/{object_id}/update-title/';
};

export type UpdateNodeTitleViewResponses = {
    /**
     * OK
     */
    200: NodeDetailSchema;
};

export type UpdateNodeTitleViewResponse = UpdateNodeTitleViewResponses[keyof UpdateNodeTitleViewResponses];
