// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateUnitBookingViewData, CreateUnitBookingViewResponses, CreateUnitViewData, CreateUnitViewResponses, CreateVillaVillekullaProjectViewData, CreateVillaVillekullaProjectViewResponses, DeleteRentalProjectViewData, DeleteRentalProjectViewResponses, DeleteUnitBookingViewData, DeleteUnitBookingViewResponses, GetRentalProjectViewData, GetRentalProjectViewResponses, GetUnitCalendarViewData, GetUnitCalendarViewResponses, ListProjectMembersViewData, ListProjectMembersViewResponses, ListUnitsViewData, ListUnitsViewResponses, PaginateVillaVillekullaProjectsViewData, PaginateVillaVillekullaProjectsViewResponses, ShareVillaVillekullaProjectViewData, ShareVillaVillekullaProjectViewResponses, UnshareRentalProjectViewData, UnshareRentalProjectViewResponses, UpdateRentalProjectViewData, UpdateRentalProjectViewResponses, UpdateUnitBookingViewData, UpdateUnitBookingViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateVillaVillekullaProjectsView = <ThrowOnError extends boolean = false>(options?: Options<PaginateVillaVillekullaProjectsViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateVillaVillekullaProjectsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/',
    ...options
});

/**
 * Post
 */
export const createVillaVillekullaProjectView = <ThrowOnError extends boolean = false>(options: Options<CreateVillaVillekullaProjectViewData, ThrowOnError>) => (options.client ?? client).post<CreateVillaVillekullaProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<DeleteRentalProjectViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteRentalProjectViewResponses, unknown, ThrowOnError>({
    url: '/api/villa-villekulla/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<GetRentalProjectViewData, ThrowOnError>) => (options.client ?? client).get<GetRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<UpdateRentalProjectViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const shareVillaVillekullaProjectView = <ThrowOnError extends boolean = false>(options: Options<ShareVillaVillekullaProjectViewData, ThrowOnError>) => (options.client ?? client).post<ShareVillaVillekullaProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/{object_id}/share/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unshareRentalProjectView = <ThrowOnError extends boolean = false>(options: Options<UnshareRentalProjectViewData, ThrowOnError>) => (options.client ?? client).post<UnshareRentalProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/{object_id}/unshare/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const listProjectMembersView = <ThrowOnError extends boolean = false>(options: Options<ListProjectMembersViewData, ThrowOnError>) => (options.client ?? client).get<ListProjectMembersViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/{object_id}/members/',
    ...options
});

/**
 * Get
 */
export const listUnitsView = <ThrowOnError extends boolean = false>(options: Options<ListUnitsViewData, ThrowOnError>) => (options.client ?? client).get<ListUnitsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/projects/{object_id}/units/',
    ...options
});

/**
 * Post
 */
export const createUnitView = <ThrowOnError extends boolean = false>(options: Options<CreateUnitViewData, ThrowOnError>) => (options.client ?? client).post<CreateUnitViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/units/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getUnitCalendarView = <ThrowOnError extends boolean = false>(options: Options<GetUnitCalendarViewData, ThrowOnError>) => (options.client ?? client).get<GetUnitCalendarViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/units/{unit_id}/bookings/',
    ...options
});

/**
 * Post
 */
export const createUnitBookingView = <ThrowOnError extends boolean = false>(options: Options<CreateUnitBookingViewData, ThrowOnError>) => (options.client ?? client).post<CreateUnitBookingViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/bookings/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteUnitBookingView = <ThrowOnError extends boolean = false>(options: Options<DeleteUnitBookingViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteUnitBookingViewResponses, unknown, ThrowOnError>({
    url: '/api/villa-villekulla/bookings/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Patch
 */
export const updateUnitBookingView = <ThrowOnError extends boolean = false>(options: Options<UpdateUnitBookingViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateUnitBookingViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/villa-villekulla/bookings/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
