# Generated by Django 5.2 on 2025-05-18 12:24

import blocks.enums.block_types
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(blank=True, default='')),
                ('b', models.IntegerField(blank=True, default=0)),
                ('c', models.BooleanField(blank=True, default=False)),
                ('block_type', models.CharField(blank=True, choices=[(blocks.enums.block_types.BlockTypes['ROUND'], blocks.enums.block_types.BlockTypes['ROUND']), (blocks.enums.block_types.BlockTypes['SQUARE'], blocks.enums.block_types.BlockTypes['SQUARE']), (blocks.enums.block_types.BlockTypes['TRIANGLE'], blocks.enums.block_types.BlockTypes['TRIANGLE'])], default=blocks.enums.block_types.BlockTypes['ROUND'], max_length=255)),
            ],
        ),
    ]
