# Generated by Django 5.2.9 on 2026-06-12 11:36

import apartment_hunt.enums.contact_method
import apartment_hunt.enums.currency
import apartment_hunt.enums.project_role
import apartment_hunt.enums.prospect_status
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('saw', 'saw'), ('contacted', 'contacted'), ('waiting_for_invitation', 'waiting_for_invitation'), ('saw_waiting_for_them', 'saw_waiting_for_them'), ('need_to_decide', 'need_to_decide'), ('declined', 'declined'), ('accepted', 'accepted'), ('signed', 'signed')], default=apartment_hunt.enums.prospect_status.ProspectStatus['SAW'], max_length=32)),
                ('town', models.CharField(blank=True, default='', max_length=255)),
                ('full_address', models.CharField(blank=True, default='', max_length=512)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('via_agency', models.BooleanField(blank=True, default=False)),
                ('agency_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_tax_benefit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_protected_room', models.BooleanField(blank=True, default=False)),
                ('liked_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('size_sqm', models.IntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('listing_url', models.CharField(blank=True, default='', max_length=1024)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1024)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartment_hunt.apartmentprospect')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProspectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('facebook', 'facebook'), ('whatsapp', 'whatsapp'), ('phone', 'phone'), ('email', 'email'), ('agency', 'agency'), ('other', 'other')], default=apartment_hunt.enums.contact_method.ContactMethod['OTHER'], max_length=16)),
                ('value', models.CharField(blank=True, default='', max_length=512)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='apartment_hunt.apartmentprospect')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, choices=[('nis', 'nis'), ('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp')], default=apartment_hunt.enums.currency.Currency['NIS'], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rental_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='apartmentprospect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='apartment_hunt.rentalproject'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('owner', 'owner'), ('collaborator', 'collaborator')], default=apartment_hunt.enums.project_role.ProjectRole['COLLABORATOR'], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_hunt_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='apartment_hunt.rentalproject')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership')],
            },
        ),
    ]
