# Generated by Django 5.2.9 on 2026-06-12 12:06

import apartment_hunt.enums.project_status
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproject',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('finished', 'finished')], default=apartment_hunt.enums.project_status.ProjectStatus['ACTIVE'], max_length=16),
        ),
    ]
