# Generated by Django 5.2.9 on 2026-06-20 09:25

import apartment_hunt.enums.family_status
import apartment_hunt.enums.project_app
import apartment_hunt.enums.renter_status
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_hunt', '0002_rentalproject_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproject',
            name='app',
            field=models.CharField(blank=True, choices=[('apartment_hunt', 'apartment_hunt'), ('renters_crm', 'renters_crm')], default=apartment_hunt.enums.project_app.ProjectApp['APARTMENT_HUNT'], max_length=32),
        ),
        migrations.AddField(
            model_name='rentalproject',
            name='initial_asked_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RenterProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('contacted', 'contacted'), ('scheduled_to_see', 'scheduled_to_see'), ('visited', 'visited'), ('declined', 'declined'), ('want_to_sign', 'want_to_sign'), ('signed', 'signed')], default=apartment_hunt.enums.renter_status.RenterStatus['CONTACTED'], max_length=32)),
                ('saw_apartment', models.BooleanField(blank=True, default=False)),
                ('visit_time', models.DateTimeField(blank=True, null=True)),
                ('has_animals', models.BooleanField(blank=True, default=False)),
                ('long_term', models.BooleanField(blank=True, default=False)),
                ('family_status', models.CharField(blank=True, choices=[('family_with_children', 'family_with_children'), ('couple', 'couple'), ('single', 'single')], default=apartment_hunt.enums.family_status.FamilyStatus['SINGLE'], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('agreed_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_renter_prospects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_prospects', to='apartment_hunt.rentalproject')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
