# Generated by Django 5.2.9 on 2026-06-20 10:29

import apartment_hunt.enums.project_app
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_hunt', '0003_rentalproject_app_rentalproject_initial_asked_rent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproject',
            name='app',
            field=models.CharField(blank=True, choices=[('apartment_hunt', 'apartment_hunt'), ('renters_crm', 'renters_crm'), ('villa_villekulla', 'villa_villekulla')], default=apartment_hunt.enums.project_app.ProjectApp['APARTMENT_HUNT'], max_length=32),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='apartment_hunt.rentalproject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_bookings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apartment_hunt.unit')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
    ]
