# Generated by Django 5.2.9 on 2026-06-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_booked_for(apps, schema_editor):
    UnitBooking = apps.get_model('apartment_hunt', 'UnitBooking')
    UnitBooking.objects.filter(booked_for__isnull=True).update(booked_for=models.F('created_by'))


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_hunt', '0004_alter_rentalproject_app_unit_unitbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbooking',
            name='booked_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_bookings_as_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_booked_for, migrations.RunPython.noop),
    ]
