// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * FullConfigurationsOutput
 */
export type FullConfigurationsOutput = {
    /**
     * Timezones
     */
    timezones: Array<string>;
    /**
     * Cloudinary Cloud Name
     */
    cloudinary_cloud_name: string | null;
    /**
     * Google Client Id
     */
    google_client_id: string | null;
};

export type FullConfigurationsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/configurations/';
};

export type FullConfigurationsViewResponses = {
    /**
     * OK
     */
    200: FullConfigurationsOutput;
};

export type FullConfigurationsViewResponse = FullConfigurationsViewResponses[keyof FullConfigurationsViewResponses];
