// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * OpenAICostsOutput
 */
export type OpenAiCostsOutput = {
    /**
     * Currency
     */
    currency: string;
    /**
     * Month To Date
     */
    month_to_date: number;
    /**
     * Last 30 Days
     */
    last_30_days: number;
    /**
     * Last 7 Days
     */
    last_7_days: number;
    /**
     * Today
     */
    today: number;
    /**
     * Fetched At
     */
    fetched_at: string;
};

export type GetOpenAiCostsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/my-dashboard/openai-costs/';
};

export type GetOpenAiCostsViewResponses = {
    /**
     * OK
     */
    200: OpenAiCostsOutput;
};

export type GetOpenAiCostsViewResponse = GetOpenAiCostsViewResponses[keyof GetOpenAiCostsViewResponses];
