// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ArchiveTaskProjectViewData, ArchiveTaskProjectViewResponses, CreateTaskProjectViewData, CreateTaskProjectViewResponses, CreateTaskViewData, CreateTaskViewResponses, DeleteTaskProjectViewData, DeleteTaskProjectViewResponses, DeleteTaskViewData, DeleteTaskViewResponses, GetTaskProjectViewData, GetTaskProjectViewResponses, GetTaskViewData, GetTaskViewResponses, ListTaskProjectMembersViewData, ListTaskProjectMembersViewResponses, PaginateTaskProjectsViewData, PaginateTaskProjectsViewResponses, PaginateTasksViewData, PaginateTasksViewResponses, ShareTaskProjectViewData, ShareTaskProjectViewResponses, UnarchiveTaskProjectViewData, UnarchiveTaskProjectViewResponses, UnshareTaskProjectViewData, UnshareTaskProjectViewResponses, UpdateTaskProjectViewData, UpdateTaskProjectViewResponses, UpdateTaskViewData, UpdateTaskViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateTaskProjectsView = <ThrowOnError extends boolean = false>(options?: Options<PaginateTaskProjectsViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateTaskProjectsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/',
    ...options
});

/**
 * Post
 */
export const createTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<CreateTaskProjectViewData, ThrowOnError>) => (options.client ?? client).post<CreateTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskProjectViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteTaskProjectViewResponses, unknown, ThrowOnError>({
    url: '/api/task-management/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<GetTaskProjectViewData, ThrowOnError>) => (options.client ?? client).get<GetTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<UpdateTaskProjectViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const shareTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<ShareTaskProjectViewData, ThrowOnError>) => (options.client ?? client).post<ShareTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/share/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unshareTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<UnshareTaskProjectViewData, ThrowOnError>) => (options.client ?? client).post<UnshareTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/unshare/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const listTaskProjectMembersView = <ThrowOnError extends boolean = false>(options: Options<ListTaskProjectMembersViewData, ThrowOnError>) => (options.client ?? client).get<ListTaskProjectMembersViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/members/',
    ...options
});

/**
 * Post
 */
export const archiveTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<ArchiveTaskProjectViewData, ThrowOnError>) => (options.client ?? client).post<ArchiveTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/archive/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unarchiveTaskProjectView = <ThrowOnError extends boolean = false>(options: Options<UnarchiveTaskProjectViewData, ThrowOnError>) => (options.client ?? client).post<UnarchiveTaskProjectViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{object_id}/unarchive/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pagination
 */
export const paginateTasksView = <ThrowOnError extends boolean = false>(options: Options<PaginateTasksViewData, ThrowOnError>) => (options.client ?? client).get<PaginateTasksViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/projects/{project_id}/tasks/',
    ...options
});

/**
 * Post
 */
export const createTaskView = <ThrowOnError extends boolean = false>(options: Options<CreateTaskViewData, ThrowOnError>) => (options.client ?? client).post<CreateTaskViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/tasks/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteTaskView = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteTaskViewResponses, unknown, ThrowOnError>({
    url: '/api/task-management/tasks/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getTaskView = <ThrowOnError extends boolean = false>(options: Options<GetTaskViewData, ThrowOnError>) => (options.client ?? client).get<GetTaskViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/tasks/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateTaskView = <ThrowOnError extends boolean = false>(options: Options<UpdateTaskViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateTaskViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/task-management/tasks/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
