// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateTaskProjectsFilterSchema
 */
export type PaginateTaskProjectsFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * PaginationOutput[TaskProjectSchema]
 */
export type PaginationOutputTaskProjectSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<TaskProjectSchema>;
};

/**
 * ProjectStatus
 */
export type ProjectStatus = 'active' | 'archived';

/**
 * TaskProjectSchema
 */
export type TaskProjectSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: ProjectStatus;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Owner Username
     */
    owner_username: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Task Count
     */
    task_count: number;
    /**
     * Open Task Count
     */
    open_task_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateTaskProjectSchema
 */
export type CreateTaskProjectSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateTaskProjectSchema
 */
export type UpdateTaskProjectSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectRole
 */
export type ProjectRole = 'owner' | 'collaborator';

/**
 * ShareTaskProjectSchema
 */
export type ShareTaskProjectSchema = {
    /**
     * Identifier
     */
    identifier: string;
    role?: ProjectRole;
};

/**
 * UnshareTaskProjectSchema
 */
export type UnshareTaskProjectSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * ProjectMembersSchema
 */
export type ProjectMembersSchema = {
    /**
     * Members
     */
    members: Array<ProjectMembershipSchema>;
};

/**
 * ProjectMembershipSchema
 */
export type ProjectMembershipSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name: string;
    role: ProjectRole;
};

/**
 * PaginateTasksFilterSchema
 */
export type PaginateTasksFilterSchema = {
    /**
     * Status
     */
    status?: string | null;
    /**
     * Priority
     */
    priority?: string | null;
};

/**
 * TasksByProjectPath
 */
export type TasksByProjectPath = {
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * PaginationOutput[TaskSchema]
 */
export type PaginationOutputTaskSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<TaskSchema>;
};

/**
 * TaskPriority
 */
export type TaskPriority = 'none' | 'low' | 'medium' | 'high' | 'urgent';

/**
 * TaskSchema
 */
export type TaskSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Parent Id
     */
    parent_id: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: TaskStatus;
    priority: TaskPriority;
    /**
     * Due At
     */
    due_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Order
     */
    order: number;
    /**
     * Itinerary List Id
     */
    itinerary_list_id: number | null;
    /**
     * Itinerary List Name
     */
    itinerary_list_name: string | null;
    /**
     * Subtask Count
     */
    subtask_count: number;
    /**
     * Done Subtask Count
     */
    done_subtask_count: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'todo' | 'in_progress' | 'done';

/**
 * CreateTaskSchema
 */
export type CreateTaskSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus | null;
    priority?: TaskPriority | null;
    /**
     * Due At
     */
    due_at?: string | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Itinerary List Id
     */
    itinerary_list_id?: number | null;
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * TaskWritableSchema
 */
export type TaskWritableSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus | null;
    priority?: TaskPriority | null;
    /**
     * Due At
     */
    due_at?: string | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Itinerary List Id
     */
    itinerary_list_id?: number | null;
};

export type PaginateTaskProjectsViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/task-management/projects/';
};

export type PaginateTaskProjectsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputTaskProjectSchema;
};

export type PaginateTaskProjectsViewResponse = PaginateTaskProjectsViewResponses[keyof PaginateTaskProjectsViewResponses];

export type CreateTaskProjectViewData = {
    body: CreateTaskProjectSchema;
    path?: never;
    query?: never;
    url: '/api/task-management/projects/';
};

export type CreateTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type CreateTaskProjectViewResponse = CreateTaskProjectViewResponses[keyof CreateTaskProjectViewResponses];

export type DeleteTaskProjectViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/';
};

export type DeleteTaskProjectViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskProjectViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/';
};

export type GetTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type GetTaskProjectViewResponse = GetTaskProjectViewResponses[keyof GetTaskProjectViewResponses];

export type UpdateTaskProjectViewData = {
    body: UpdateTaskProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/';
};

export type UpdateTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type UpdateTaskProjectViewResponse = UpdateTaskProjectViewResponses[keyof UpdateTaskProjectViewResponses];

export type ShareTaskProjectViewData = {
    body: ShareTaskProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/share/';
};

export type ShareTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type ShareTaskProjectViewResponse = ShareTaskProjectViewResponses[keyof ShareTaskProjectViewResponses];

export type UnshareTaskProjectViewData = {
    body: UnshareTaskProjectSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/unshare/';
};

export type UnshareTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type UnshareTaskProjectViewResponse = UnshareTaskProjectViewResponses[keyof UnshareTaskProjectViewResponses];

export type ListTaskProjectMembersViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/members/';
};

export type ListTaskProjectMembersViewResponses = {
    /**
     * OK
     */
    200: ProjectMembersSchema;
};

export type ListTaskProjectMembersViewResponse = ListTaskProjectMembersViewResponses[keyof ListTaskProjectMembersViewResponses];

export type ArchiveTaskProjectViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/archive/';
};

export type ArchiveTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type ArchiveTaskProjectViewResponse = ArchiveTaskProjectViewResponses[keyof ArchiveTaskProjectViewResponses];

export type UnarchiveTaskProjectViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/projects/{object_id}/unarchive/';
};

export type UnarchiveTaskProjectViewResponses = {
    /**
     * OK
     */
    200: TaskProjectSchema;
};

export type UnarchiveTaskProjectViewResponse = UnarchiveTaskProjectViewResponses[keyof UnarchiveTaskProjectViewResponses];

export type PaginateTasksViewData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Priority
         */
        priority?: string | null;
    };
    url: '/api/task-management/projects/{project_id}/tasks/';
};

export type PaginateTasksViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputTaskSchema;
};

export type PaginateTasksViewResponse = PaginateTasksViewResponses[keyof PaginateTasksViewResponses];

export type CreateTaskViewData = {
    body: CreateTaskSchema;
    path?: never;
    query?: never;
    url: '/api/task-management/tasks/';
};

export type CreateTaskViewResponses = {
    /**
     * OK
     */
    200: TaskSchema;
};

export type CreateTaskViewResponse = CreateTaskViewResponses[keyof CreateTaskViewResponses];

export type DeleteTaskViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/tasks/{object_id}/';
};

export type DeleteTaskViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/tasks/{object_id}/';
};

export type GetTaskViewResponses = {
    /**
     * OK
     */
    200: TaskSchema;
};

export type GetTaskViewResponse = GetTaskViewResponses[keyof GetTaskViewResponses];

export type UpdateTaskViewData = {
    body: TaskWritableSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/task-management/tasks/{object_id}/';
};

export type UpdateTaskViewResponses = {
    /**
     * OK
     */
    200: TaskSchema;
};

export type UpdateTaskViewResponse = UpdateTaskViewResponses[keyof UpdateTaskViewResponses];
