// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateItineraryListViewData, ActivateItineraryListViewResponses, CreateItineraryItemViewData, CreateItineraryItemViewResponses, CreateItineraryListViewData, CreateItineraryListViewResponses, DeleteItineraryItemViewData, DeleteItineraryItemViewResponses, DeleteItineraryListViewData, DeleteItineraryListViewResponses, FinishItineraryListViewData, FinishItineraryListViewResponses, GetItineraryItemViewData, GetItineraryItemViewResponses, GetItineraryListViewData, GetItineraryListViewResponses, ListItineraryListMembersViewData, ListItineraryListMembersViewResponses, PaginateItineraryItemsViewData, PaginateItineraryItemsViewResponses, PaginateItineraryListsViewData, PaginateItineraryListsViewResponses, ShareItineraryListViewData, ShareItineraryListViewResponses, UnshareItineraryListViewData, UnshareItineraryListViewResponses, UpdateItineraryItemViewData, UpdateItineraryItemViewResponses, UpdateItineraryListViewData, UpdateItineraryListViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateItineraryListsView = <ThrowOnError extends boolean = false>(options?: Options<PaginateItineraryListsViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateItineraryListsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/',
    ...options
});

/**
 * Post
 */
export const createItineraryListView = <ThrowOnError extends boolean = false>(options: Options<CreateItineraryListViewData, ThrowOnError>) => (options.client ?? client).post<CreateItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteItineraryListView = <ThrowOnError extends boolean = false>(options: Options<DeleteItineraryListViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteItineraryListViewResponses, unknown, ThrowOnError>({
    url: '/api/itinerary-lists/lists/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getItineraryListView = <ThrowOnError extends boolean = false>(options: Options<GetItineraryListViewData, ThrowOnError>) => (options.client ?? client).get<GetItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateItineraryListView = <ThrowOnError extends boolean = false>(options: Options<UpdateItineraryListViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const shareItineraryListView = <ThrowOnError extends boolean = false>(options: Options<ShareItineraryListViewData, ThrowOnError>) => (options.client ?? client).post<ShareItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/share/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unshareItineraryListView = <ThrowOnError extends boolean = false>(options: Options<UnshareItineraryListViewData, ThrowOnError>) => (options.client ?? client).post<UnshareItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/unshare/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const listItineraryListMembersView = <ThrowOnError extends boolean = false>(options: Options<ListItineraryListMembersViewData, ThrowOnError>) => (options.client ?? client).get<ListItineraryListMembersViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/members/',
    ...options
});

/**
 * Post
 */
export const activateItineraryListView = <ThrowOnError extends boolean = false>(options: Options<ActivateItineraryListViewData, ThrowOnError>) => (options.client ?? client).post<ActivateItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/activate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const finishItineraryListView = <ThrowOnError extends boolean = false>(options: Options<FinishItineraryListViewData, ThrowOnError>) => (options.client ?? client).post<FinishItineraryListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{object_id}/finish/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pagination
 */
export const paginateItineraryItemsView = <ThrowOnError extends boolean = false>(options: Options<PaginateItineraryItemsViewData, ThrowOnError>) => (options.client ?? client).get<PaginateItineraryItemsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/lists/{list_id}/items/',
    ...options
});

/**
 * Post
 */
export const createItineraryItemView = <ThrowOnError extends boolean = false>(options: Options<CreateItineraryItemViewData, ThrowOnError>) => (options.client ?? client).post<CreateItineraryItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/items/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteItineraryItemView = <ThrowOnError extends boolean = false>(options: Options<DeleteItineraryItemViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteItineraryItemViewResponses, unknown, ThrowOnError>({
    url: '/api/itinerary-lists/items/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getItineraryItemView = <ThrowOnError extends boolean = false>(options: Options<GetItineraryItemViewData, ThrowOnError>) => (options.client ?? client).get<GetItineraryItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/items/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateItineraryItemView = <ThrowOnError extends boolean = false>(options: Options<UpdateItineraryItemViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateItineraryItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/itinerary-lists/items/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
