// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateItineraryListsFilterSchema
 */
export type PaginateItineraryListsFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * ItineraryListSchema
 */
export type ItineraryListSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: ListStatus;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Owner Username
     */
    owner_username: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Item Count
     */
    item_count: number;
    /**
     * Task Count
     */
    task_count: number;
    /**
     * Activated At
     */
    activated_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ListStatus
 */
export type ListStatus = 'standby' | 'active';

/**
 * PaginationOutput[ItineraryListSchema]
 */
export type PaginationOutputItineraryListSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ItineraryListSchema>;
};

/**
 * CreateItineraryListSchema
 */
export type CreateItineraryListSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateItineraryListSchema
 */
export type UpdateItineraryListSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ListRole
 */
export type ListRole = 'owner' | 'collaborator';

/**
 * ShareItineraryListSchema
 */
export type ShareItineraryListSchema = {
    /**
     * Identifier
     */
    identifier: string;
    role?: ListRole;
};

/**
 * UnshareItineraryListSchema
 */
export type UnshareItineraryListSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * ListMembersSchema
 */
export type ListMembersSchema = {
    /**
     * Members
     */
    members: Array<ListMembershipSchema>;
    /**
     * Pending Invitations
     */
    pending_invitations: Array<PendingInvitationSchema>;
};

/**
 * ListMembershipSchema
 */
export type ListMembershipSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name: string;
    role: ListRole;
};

/**
 * PendingInvitationSchema
 */
export type PendingInvitationSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PaginateItineraryItemsFilterSchema
 */
export type PaginateItineraryItemsFilterSchema = {
    /**
     * Status
     */
    status?: string | null;
};

/**
 * ItemsByListPath
 */
export type ItemsByListPath = {
    /**
     * List Id
     */
    list_id: number;
};

/**
 * ItemStatus
 */
export type ItemStatus = 'need_to_buy' | 'in_the_house' | 'ready' | 'in_the_car';

/**
 * ItineraryItemSchema
 */
export type ItineraryItemSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Itinerary List Id
     */
    itinerary_list_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: ItemStatus;
    /**
     * Order
     */
    order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PaginationOutput[ItineraryItemSchema]
 */
export type PaginationOutputItineraryItemSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ItineraryItemSchema>;
};

/**
 * CreateItineraryItemSchema
 */
export type CreateItineraryItemSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    status?: ItemStatus | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Itinerary List Id
     */
    itinerary_list_id: number;
};

/**
 * ItineraryItemWritableSchema
 */
export type ItineraryItemWritableSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: ItemStatus | null;
    /**
     * Order
     */
    order?: number | null;
};

/**
 * PaginateItineraryTasksFilterSchema
 */
export type PaginateItineraryTasksFilterSchema = {
    /**
     * Status
     */
    status?: string | null;
};

/**
 * TasksByListPath
 */
export type TasksByListPath = {
    /**
     * List Id
     */
    list_id: number;
};

/**
 * ItineraryTaskSchema
 */
export type ItineraryTaskSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Itinerary List Id
     */
    itinerary_list_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    status: TaskStatus;
    /**
     * Order
     */
    order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PaginationOutput[ItineraryTaskSchema]
 */
export type PaginationOutputItineraryTaskSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ItineraryTaskSchema>;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'to_do' | 'done';

/**
 * CreateItineraryTaskSchema
 */
export type CreateItineraryTaskSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Itinerary List Id
     */
    itinerary_list_id: number;
};

/**
 * ItineraryTaskWritableSchema
 */
export type ItineraryTaskWritableSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus | null;
    /**
     * Order
     */
    order?: number | null;
};

export type PaginateItineraryListsViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/itinerary-lists/lists/';
};

export type PaginateItineraryListsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputItineraryListSchema;
};

export type PaginateItineraryListsViewResponse = PaginateItineraryListsViewResponses[keyof PaginateItineraryListsViewResponses];

export type CreateItineraryListViewData = {
    body: CreateItineraryListSchema;
    path?: never;
    query?: never;
    url: '/api/itinerary-lists/lists/';
};

export type CreateItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type CreateItineraryListViewResponse = CreateItineraryListViewResponses[keyof CreateItineraryListViewResponses];

export type DeleteItineraryListViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/';
};

export type DeleteItineraryListViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetItineraryListViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/';
};

export type GetItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type GetItineraryListViewResponse = GetItineraryListViewResponses[keyof GetItineraryListViewResponses];

export type UpdateItineraryListViewData = {
    body: UpdateItineraryListSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/';
};

export type UpdateItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type UpdateItineraryListViewResponse = UpdateItineraryListViewResponses[keyof UpdateItineraryListViewResponses];

export type ShareItineraryListViewData = {
    body: ShareItineraryListSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/share/';
};

export type ShareItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type ShareItineraryListViewResponse = ShareItineraryListViewResponses[keyof ShareItineraryListViewResponses];

export type UnshareItineraryListViewData = {
    body: UnshareItineraryListSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/unshare/';
};

export type UnshareItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type UnshareItineraryListViewResponse = UnshareItineraryListViewResponses[keyof UnshareItineraryListViewResponses];

export type ListItineraryListMembersViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/members/';
};

export type ListItineraryListMembersViewResponses = {
    /**
     * OK
     */
    200: ListMembersSchema;
};

export type ListItineraryListMembersViewResponse = ListItineraryListMembersViewResponses[keyof ListItineraryListMembersViewResponses];

export type ActivateItineraryListViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/activate/';
};

export type ActivateItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type ActivateItineraryListViewResponse = ActivateItineraryListViewResponses[keyof ActivateItineraryListViewResponses];

export type FinishItineraryListViewData = {
    body: EmptySchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/lists/{object_id}/finish/';
};

export type FinishItineraryListViewResponses = {
    /**
     * OK
     */
    200: ItineraryListSchema;
};

export type FinishItineraryListViewResponse = FinishItineraryListViewResponses[keyof FinishItineraryListViewResponses];

export type PaginateItineraryItemsViewData = {
    body?: never;
    path: {
        /**
         * List Id
         */
        list_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/itinerary-lists/lists/{list_id}/items/';
};

export type PaginateItineraryItemsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputItineraryItemSchema;
};

export type PaginateItineraryItemsViewResponse = PaginateItineraryItemsViewResponses[keyof PaginateItineraryItemsViewResponses];

export type CreateItineraryItemViewData = {
    body: CreateItineraryItemSchema;
    path?: never;
    query?: never;
    url: '/api/itinerary-lists/items/';
};

export type CreateItineraryItemViewResponses = {
    /**
     * OK
     */
    200: ItineraryItemSchema;
};

export type CreateItineraryItemViewResponse = CreateItineraryItemViewResponses[keyof CreateItineraryItemViewResponses];

export type DeleteItineraryItemViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/items/{object_id}/';
};

export type DeleteItineraryItemViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetItineraryItemViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/items/{object_id}/';
};

export type GetItineraryItemViewResponses = {
    /**
     * OK
     */
    200: ItineraryItemSchema;
};

export type GetItineraryItemViewResponse = GetItineraryItemViewResponses[keyof GetItineraryItemViewResponses];

export type UpdateItineraryItemViewData = {
    body: ItineraryItemWritableSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/items/{object_id}/';
};

export type UpdateItineraryItemViewResponses = {
    /**
     * OK
     */
    200: ItineraryItemSchema;
};

export type UpdateItineraryItemViewResponse = UpdateItineraryItemViewResponses[keyof UpdateItineraryItemViewResponses];

export type PaginateItineraryTasksViewData = {
    body?: never;
    path: {
        /**
         * List Id
         */
        list_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/itinerary-lists/lists/{list_id}/tasks/';
};

export type PaginateItineraryTasksViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputItineraryTaskSchema;
};

export type PaginateItineraryTasksViewResponse = PaginateItineraryTasksViewResponses[keyof PaginateItineraryTasksViewResponses];

export type CreateItineraryTaskViewData = {
    body: CreateItineraryTaskSchema;
    path?: never;
    query?: never;
    url: '/api/itinerary-lists/tasks/';
};

export type CreateItineraryTaskViewResponses = {
    /**
     * OK
     */
    200: ItineraryTaskSchema;
};

export type CreateItineraryTaskViewResponse = CreateItineraryTaskViewResponses[keyof CreateItineraryTaskViewResponses];

export type DeleteItineraryTaskViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/tasks/{object_id}/';
};

export type DeleteItineraryTaskViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetItineraryTaskViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/tasks/{object_id}/';
};

export type GetItineraryTaskViewResponses = {
    /**
     * OK
     */
    200: ItineraryTaskSchema;
};

export type GetItineraryTaskViewResponse = GetItineraryTaskViewResponses[keyof GetItineraryTaskViewResponses];

export type UpdateItineraryTaskViewData = {
    body: ItineraryTaskWritableSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/itinerary-lists/tasks/{object_id}/';
};

export type UpdateItineraryTaskViewResponses = {
    /**
     * OK
     */
    200: ItineraryTaskSchema;
};

export type UpdateItineraryTaskViewResponse = UpdateItineraryTaskViewResponses[keyof UpdateItineraryTaskViewResponses];
