// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * JoinPreviewQuerySchema
 */
export type JoinPreviewQuerySchema = {
    /**
     * Token
     */
    token: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * SpecialDateCalendarJoinPreviewSchema
 */
export type SpecialDateCalendarJoinPreviewSchema = {
    /**
     * Calendar Name
     */
    calendar_name: string;
    /**
     * Owner Name
     */
    owner_name: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Event Count
     */
    event_count: number;
};

export type GetSpecialDateCalendarJoinPreviewViewData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/special-dates-public/join-preview/';
};

export type GetSpecialDateCalendarJoinPreviewViewResponses = {
    /**
     * OK
     */
    200: SpecialDateCalendarJoinPreviewSchema;
};

export type GetSpecialDateCalendarJoinPreviewViewResponse = GetSpecialDateCalendarJoinPreviewViewResponses[keyof GetSpecialDateCalendarJoinPreviewViewResponses];
