# Generated by Django 5.2.9 on 2026-09-28 12:11

import django.db.models.deletion
import special_dates.enums.special_date_category
import special_dates.enums.special_date_recurrence
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('after_sunset', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('birthday', 'birthday'), ('anniversary', 'anniversary'), ('memorial', 'memorial'), ('other', 'other')], default=special_dates.enums.special_date_category.SpecialDateCategory['BIRTHDAY'], max_length=32)),
                ('recurrence', models.CharField(choices=[('both', 'both'), ('gregorian', 'gregorian'), ('hebrew', 'hebrew')], default=special_dates.enums.special_date_recurrence.SpecialDateRecurrence['BOTH'], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['owner', 'date'], name='special_dat_owner_i_1b8dbc_idx')],
            },
        ),
    ]
