# Generated by Django 5.2.9 on 2026-09-28 13:10

import special_dates.enums.calendar_type
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_dates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialdate',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='specialdate',
            name='special_dat_owner_i_1b8dbc_idx',
        ),
        migrations.RenameField(
            model_name='specialdate',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='specialdate',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='specialdate',
            name='input_calendar',
            field=models.CharField(choices=[('gregorian', 'gregorian'), ('hebrew', 'hebrew')], default=special_dates.enums.calendar_type.CalendarType['GREGORIAN'], max_length=16),
        ),
        migrations.AddField(
            model_name='specialdate',
            name='remind_gregorian',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialdate',
            name='remind_hebrew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='specialdate',
            index=models.Index(fields=['owner', 'name'], name='special_dat_owner_i_667675_idx'),
        ),
    ]
