# Generated by Django 5.2.9 on 2026-09-28 15:22

import django.db.models.deletion
import special_dates.enums.special_date_calendar_role
import special_dates.models.special_date_calendar
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_dates', '0002_alter_specialdate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDateCalendarMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('editor', 'editor')], default=special_dates.enums.special_date_calendar_role.SpecialDateCalendarRole['EDITOR'], max_length=16)),
                ('hide_from_upcoming', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='specialdate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpecialDateCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('join_token', models.CharField(default=special_dates.models.special_date_calendar.generate_join_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_special_date_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='specialdate',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to='special_dates.specialdatecalendar'),
        ),
        migrations.AddIndex(
            model_name='specialdate',
            index=models.Index(fields=['calendar', 'name'], name='special_dat_calenda_5bfc47_idx'),
        ),
        migrations.AddField(
            model_name='specialdatecalendarmembership',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='special_dates.specialdatecalendar'),
        ),
        migrations.AddField(
            model_name='specialdatecalendarmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_date_calendar_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='specialdatecalendarmembership',
            constraint=models.UniqueConstraint(fields=('calendar', 'user'), name='unique_special_date_calendar_member'),
        ),
    ]
