# Generated by Django 5.2.9 on 2026-09-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_dates', '0003_specialdatecalendarmembership_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='specialdate',
            name='special_dat_owner_i_667675_idx',
        ),
        migrations.RenameField(
            model_name='specialdate',
            old_name='owner',
            new_name='created_by',
        ),
    ]
