// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateShoppingItemViewData, CreateShoppingItemViewResponses, CreateShoppingListViewData, CreateShoppingListViewResponses, DeleteShoppingItemViewData, DeleteShoppingItemViewResponses, DeleteShoppingListViewData, DeleteShoppingListViewResponses, GetShoppingListViewData, GetShoppingListViewResponses, ListShoppingListMembersViewData, ListShoppingListMembersViewResponses, PaginateShoppingItemsViewData, PaginateShoppingItemsViewResponses, PaginateShoppingListsViewData, PaginateShoppingListsViewResponses, ShareShoppingListViewData, ShareShoppingListViewResponses, UnshareShoppingListViewData, UnshareShoppingListViewResponses, UpdateShoppingItemViewData, UpdateShoppingItemViewResponses, UpdateShoppingListViewData, UpdateShoppingListViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginateShoppingListsView = <ThrowOnError extends boolean = false>(options?: Options<PaginateShoppingListsViewData, ThrowOnError>) => (options?.client ?? client).get<PaginateShoppingListsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/',
    ...options
});

/**
 * Post
 */
export const createShoppingListView = <ThrowOnError extends boolean = false>(options: Options<CreateShoppingListViewData, ThrowOnError>) => (options.client ?? client).post<CreateShoppingListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteShoppingListView = <ThrowOnError extends boolean = false>(options: Options<DeleteShoppingListViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteShoppingListViewResponses, unknown, ThrowOnError>({
    url: '/api/shopping-lists/lists/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const getShoppingListView = <ThrowOnError extends boolean = false>(options: Options<GetShoppingListViewData, ThrowOnError>) => (options.client ?? client).get<GetShoppingListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateShoppingListView = <ThrowOnError extends boolean = false>(options: Options<UpdateShoppingListViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateShoppingListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const shareShoppingListView = <ThrowOnError extends boolean = false>(options: Options<ShareShoppingListViewData, ThrowOnError>) => (options.client ?? client).post<ShareShoppingListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/{object_id}/share/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const unshareShoppingListView = <ThrowOnError extends boolean = false>(options: Options<UnshareShoppingListViewData, ThrowOnError>) => (options.client ?? client).post<UnshareShoppingListViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/{object_id}/unshare/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const listShoppingListMembersView = <ThrowOnError extends boolean = false>(options: Options<ListShoppingListMembersViewData, ThrowOnError>) => (options.client ?? client).get<ListShoppingListMembersViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/{object_id}/members/',
    ...options
});

/**
 * Pagination
 */
export const paginateShoppingItemsView = <ThrowOnError extends boolean = false>(options: Options<PaginateShoppingItemsViewData, ThrowOnError>) => (options.client ?? client).get<PaginateShoppingItemsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/lists/{list_id}/items/',
    ...options
});

/**
 * Post
 */
export const createShoppingItemView = <ThrowOnError extends boolean = false>(options: Options<CreateShoppingItemViewData, ThrowOnError>) => (options.client ?? client).post<CreateShoppingItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/items/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteShoppingItemView = <ThrowOnError extends boolean = false>(options: Options<DeleteShoppingItemViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteShoppingItemViewResponses, unknown, ThrowOnError>({
    url: '/api/shopping-lists/items/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Patch
 */
export const updateShoppingItemView = <ThrowOnError extends boolean = false>(options: Options<UpdateShoppingItemViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateShoppingItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/shopping-lists/items/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
