// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * PaginateShoppingListsFilterSchema
 */
export type PaginateShoppingListsFilterSchema = {
    [key: string]: unknown;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * PaginationOutput[ShoppingListSchema]
 */
export type PaginationOutputShoppingListSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ShoppingListSchema>;
};

/**
 * ShoppingListSchema
 */
export type ShoppingListSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Owner Username
     */
    owner_username: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Unchecked Count
     */
    unchecked_count: number;
    /**
     * Checked Count
     */
    checked_count: number;
    /**
     * Preview Items
     */
    preview_items: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateShoppingListSchema
 */
export type CreateShoppingListSchema = {
    /**
     * Name
     */
    name: string;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * UpdateShoppingListSchema
 */
export type UpdateShoppingListSchema = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ShareShoppingListSchema
 */
export type ShareShoppingListSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * UnshareShoppingListSchema
 */
export type UnshareShoppingListSchema = {
    /**
     * Identifier
     */
    identifier: string;
};

/**
 * PendingInvitationSchema
 */
export type PendingInvitationSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ShoppingListMembersSchema
 */
export type ShoppingListMembersSchema = {
    /**
     * Members
     */
    members: Array<ShoppingListMembershipSchema>;
    /**
     * Pending Invitations
     */
    pending_invitations: Array<PendingInvitationSchema>;
};

/**
 * ShoppingListMembershipSchema
 */
export type ShoppingListMembershipSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name: string;
    role: ShoppingListRole;
};

/**
 * ShoppingListRole
 */
export type ShoppingListRole = 'owner' | 'collaborator';

/**
 * PaginateShoppingItemsFilterSchema
 */
export type PaginateShoppingItemsFilterSchema = {
    /**
     * Is Checked
     */
    is_checked?: boolean | null;
};

/**
 * ShoppingItemsByListPath
 */
export type ShoppingItemsByListPath = {
    /**
     * List Id
     */
    list_id: number;
};

/**
 * PaginationOutput[ShoppingItemSchema]
 */
export type PaginationOutputShoppingItemSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ShoppingItemSchema>;
};

/**
 * ShoppingItemSchema
 */
export type ShoppingItemSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Shopping List Id
     */
    shopping_list_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Is Checked
     */
    is_checked: boolean;
    /**
     * Checked At
     */
    checked_at: string | null;
    /**
     * Order
     */
    order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateShoppingItemSchema
 */
export type CreateShoppingItemSchema = {
    /**
     * Shopping List Id
     */
    shopping_list_id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * ShoppingItemWritableSchema
 */
export type ShoppingItemWritableSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Is Checked
     */
    is_checked?: boolean | null;
};

export type PaginateShoppingListsViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
    };
    url: '/api/shopping-lists/lists/';
};

export type PaginateShoppingListsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputShoppingListSchema;
};

export type PaginateShoppingListsViewResponse = PaginateShoppingListsViewResponses[keyof PaginateShoppingListsViewResponses];

export type CreateShoppingListViewData = {
    body: CreateShoppingListSchema;
    path?: never;
    query?: never;
    url: '/api/shopping-lists/lists/';
};

export type CreateShoppingListViewResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type CreateShoppingListViewResponse = CreateShoppingListViewResponses[keyof CreateShoppingListViewResponses];

export type DeleteShoppingListViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/lists/{object_id}/';
};

export type DeleteShoppingListViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetShoppingListViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/lists/{object_id}/';
};

export type GetShoppingListViewResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type GetShoppingListViewResponse = GetShoppingListViewResponses[keyof GetShoppingListViewResponses];

export type UpdateShoppingListViewData = {
    body: UpdateShoppingListSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/lists/{object_id}/';
};

export type UpdateShoppingListViewResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type UpdateShoppingListViewResponse = UpdateShoppingListViewResponses[keyof UpdateShoppingListViewResponses];

export type ShareShoppingListViewData = {
    body: ShareShoppingListSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/lists/{object_id}/share/';
};

export type ShareShoppingListViewResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type ShareShoppingListViewResponse = ShareShoppingListViewResponses[keyof ShareShoppingListViewResponses];

export type UnshareShoppingListViewData = {
    body: UnshareShoppingListSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/lists/{object_id}/unshare/';
};

export type UnshareShoppingListViewResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type UnshareShoppingListViewResponse = UnshareShoppingListViewResponses[keyof UnshareShoppingListViewResponses];

export type ListShoppingListMembersViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/lists/{object_id}/members/';
};

export type ListShoppingListMembersViewResponses = {
    /**
     * OK
     */
    200: ShoppingListMembersSchema;
};

export type ListShoppingListMembersViewResponse = ListShoppingListMembersViewResponses[keyof ListShoppingListMembersViewResponses];

export type PaginateShoppingItemsViewData = {
    body?: never;
    path: {
        /**
         * List Id
         */
        list_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Is Checked
         */
        is_checked?: boolean | null;
    };
    url: '/api/shopping-lists/lists/{list_id}/items/';
};

export type PaginateShoppingItemsViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputShoppingItemSchema;
};

export type PaginateShoppingItemsViewResponse = PaginateShoppingItemsViewResponses[keyof PaginateShoppingItemsViewResponses];

export type CreateShoppingItemViewData = {
    body: CreateShoppingItemSchema;
    path?: never;
    query?: never;
    url: '/api/shopping-lists/items/';
};

export type CreateShoppingItemViewResponses = {
    /**
     * OK
     */
    200: ShoppingItemSchema;
};

export type CreateShoppingItemViewResponse = CreateShoppingItemViewResponses[keyof CreateShoppingItemViewResponses];

export type DeleteShoppingItemViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/items/{object_id}/';
};

export type DeleteShoppingItemViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateShoppingItemViewData = {
    body: ShoppingItemWritableSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/shopping-lists/items/{object_id}/';
};

export type UpdateShoppingItemViewResponses = {
    /**
     * OK
     */
    200: ShoppingItemSchema;
};

export type UpdateShoppingItemViewResponse = UpdateShoppingItemViewResponses[keyof UpdateShoppingItemViewResponses];
