# Generated by Django 5.2.9 on 2026-06-13 07:52

import django.db.models.deletion
import itinerary_lists.enums.item_status
import itinerary_lists.enums.list_role
import itinerary_lists.enums.list_status
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('standby', 'standby'), ('active', 'active')], default=itinerary_lists.enums.list_status.ListStatus['STANDBY'], max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_itinerary_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('need_to_buy', 'need_to_buy'), ('in_the_house', 'in_the_house'), ('ready', 'ready'), ('in_the_car', 'in_the_car')], default=itinerary_lists.enums.item_status.ItemStatus['NEED_TO_BUY'], max_length=16)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itinerary_items', to=settings.AUTH_USER_MODEL)),
                ('itinerary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itinerary_lists.itinerarylist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('owner', 'owner'), ('collaborator', 'collaborator')], default=itinerary_lists.enums.list_role.ListRole['COLLABORATOR'], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='itinerary_lists.itinerarylist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_list_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('itinerary_list', 'user'), name='unique_itinerary_list_membership')],
            },
        ),
    ]
