# Generated by Django 5.2.9 on 2026-06-23 15:17

import django.db.models.deletion
import itinerary_lists.enums.task_status
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('to_do', 'to_do'), ('done', 'done')], default=itinerary_lists.enums.task_status.TaskStatus['TO_DO'], max_length=16)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itinerary_tasks', to=settings.AUTH_USER_MODEL)),
                ('itinerary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='itinerary_lists.itinerarylist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
