// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AdminUsersPaginationViewData, AdminUsersPaginationViewResponses, MyUserItemViewData, MyUserItemViewResponses, UpdateMyTimezoneViewData, UpdateMyTimezoneViewResponses, UpdateMyUserViewData, UpdateMyUserViewResponses, UpdateUserPermissionsViewData, UpdateUserPermissionsViewResponses, UploadUserProfileImageViewData, UploadUserProfileImageViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const myUserItemView = <ThrowOnError extends boolean = false>(options?: Options<MyUserItemViewData, ThrowOnError>) => (options?.client ?? client).get<MyUserItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/users/my/',
    ...options
});

/**
 * Pagination
 */
export const adminUsersPaginationView = <ThrowOnError extends boolean = false>(options?: Options<AdminUsersPaginationViewData, ThrowOnError>) => (options?.client ?? client).get<AdminUsersPaginationViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/users/by-admin/',
    ...options
});

/**
 * Post
 */
export const updateUserPermissionsView = <ThrowOnError extends boolean = false>(options: Options<UpdateUserPermissionsViewData, ThrowOnError>) => (options.client ?? client).post<UpdateUserPermissionsViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/users/by-admin/update-permissions/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const updateMyUserView = <ThrowOnError extends boolean = false>(options: Options<UpdateMyUserViewData, ThrowOnError>) => (options.client ?? client).post<UpdateMyUserViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/users/update-my-user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const updateMyTimezoneView = <ThrowOnError extends boolean = false>(options: Options<UpdateMyTimezoneViewData, ThrowOnError>) => (options.client ?? client).post<UpdateMyTimezoneViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/users/update-my-timezone/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const uploadUserProfileImageView = <ThrowOnError extends boolean = false>(options: Options<UploadUserProfileImageViewData, ThrowOnError>) => (options.client ?? client).post<UploadUserProfileImageViewResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/users/upload-profile-image/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
