// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * Permissions
 */
export type Permissions = 'admin' | 'editor' | 'dream_diary' | 'apartment_hunt';

/**
 * SubscriptionLimitsSchema
 */
export type SubscriptionLimitsSchema = {
    /**
     * Items
     */
    items: number;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Pic Url
     */
    pic_url: string | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Initials
     */
    initials: string;
    /**
     * Permissions
     */
    permissions: Array<Permissions>;
    subscription_limits: SubscriptionLimitsSchema;
    /**
     * Has Usable Password
     */
    has_usable_password: boolean;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * UserFilterSchema
 */
export type UserFilterSchema = {
    /**
     * Text
     */
    text?: string | null;
};

/**
 * PaginationOutput[ShortUserOutput]
 */
export type PaginationOutputShortUserOutput = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<ShortUserOutput>;
};

/**
 * ShortUserOutput
 */
export type ShortUserOutput = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Initials
     */
    initials: string;
};

/**
 * UpdateMyUserInputSchema
 */
export type UpdateMyUserInputSchema = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * Schema
 */
export type Schema = {
    [key: string]: unknown;
};

export type MyUserItemViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/my/';
};

export type MyUserItemViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type MyUserItemViewResponse = MyUserItemViewResponses[keyof MyUserItemViewResponses];

export type AdminUsersPaginationViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * Text
         */
        text?: string | null;
    };
    url: '/api/users/by-admin/';
};

export type AdminUsersPaginationViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputShortUserOutput;
};

export type AdminUsersPaginationViewResponse = AdminUsersPaginationViewResponses[keyof AdminUsersPaginationViewResponses];

export type UpdateMyUserViewData = {
    body: UpdateMyUserInputSchema;
    path?: never;
    query?: never;
    url: '/api/users/update-my-user/';
};

export type UpdateMyUserViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type UpdateMyUserViewResponse = UpdateMyUserViewResponses[keyof UpdateMyUserViewResponses];

export type UploadUserProfileImageViewData = {
    /**
     * FileParams
     */
    body: {
        /**
         * Files
         */
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/users/upload-profile-image/';
};

export type UploadUserProfileImageViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type UploadUserProfileImageViewResponse = UploadUserProfileImageViewResponses[keyof UploadUserProfileImageViewResponses];
