// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMcpConnectionInfoViewData, GetMcpConnectionInfoViewResponses, GetOAuthClientInfoViewData, GetOAuthClientInfoViewResponses, OAuthApproveViewData, OAuthApproveViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const getMcpConnectionInfoView = <ThrowOnError extends boolean = false>(options?: Options<GetMcpConnectionInfoViewData, ThrowOnError>) => (options?.client ?? client).get<GetMcpConnectionInfoViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/mcp/connection-info/',
    ...options
});

/**
 * Get
 */
export const getOAuthClientInfoView = <ThrowOnError extends boolean = false>(options: Options<GetOAuthClientInfoViewData, ThrowOnError>) => (options.client ?? client).get<GetOAuthClientInfoViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/mcp/oauth/client-info/',
    ...options
});

/**
 * Post
 */
export const oAuthApproveView = <ThrowOnError extends boolean = false>(options: Options<OAuthApproveViewData, ThrowOnError>) => (options.client ?? client).post<OAuthApproveViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/mcp/oauth/approve/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
