// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * McpConnectionInfo
 */
export type McpConnectionInfo = {
    /**
     * Mcp Url
     */
    mcp_url: string;
    /**
     * Add Connector Url
     */
    add_connector_url: string;
    /**
     * Is Publicly Reachable
     */
    is_publicly_reachable: boolean;
};

/**
 * OAuthClientInfoQuery
 */
export type OAuthClientInfoQuery = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Redirect Uri
     */
    redirect_uri: string;
};

/**
 * OAuthClientInfo
 */
export type OAuthClientInfo = {
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Redirect Host
     */
    redirect_host: string;
};

/**
 * OAuthConsentResult
 */
export type OAuthConsentResult = {
    /**
     * Redirect Url
     */
    redirect_url: string;
};

/**
 * OAuthConsentRequest
 */
export type OAuthConsentRequest = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Redirect Uri
     */
    redirect_uri: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * State
     */
    state?: string;
    /**
     * Code Challenge
     */
    code_challenge?: string;
    /**
     * Code Challenge Method
     */
    code_challenge_method?: string;
    /**
     * Resource
     */
    resource?: string;
    /**
     * Approve
     */
    approve: boolean;
};

export type GetMcpConnectionInfoViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mcp/connection-info/';
};

export type GetMcpConnectionInfoViewResponses = {
    /**
     * OK
     */
    200: McpConnectionInfo;
};

export type GetMcpConnectionInfoViewResponse = GetMcpConnectionInfoViewResponses[keyof GetMcpConnectionInfoViewResponses];

export type GetOAuthClientInfoViewData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Client Id
         */
        client_id: string;
        /**
         * Redirect Uri
         */
        redirect_uri: string;
    };
    url: '/api/mcp/oauth/client-info/';
};

export type GetOAuthClientInfoViewResponses = {
    /**
     * OK
     */
    200: OAuthClientInfo;
};

export type GetOAuthClientInfoViewResponse = GetOAuthClientInfoViewResponses[keyof GetOAuthClientInfoViewResponses];

export type OAuthApproveViewData = {
    body: OAuthConsentRequest;
    path?: never;
    query?: never;
    url: '/api/mcp/oauth/approve/';
};

export type OAuthApproveViewResponses = {
    /**
     * OK
     */
    200: OAuthConsentResult;
};

export type OAuthApproveViewResponse = OAuthApproveViewResponses[keyof OAuthApproveViewResponses];
