# Generated by Django 5.2.9 on 2026-05-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamdiaryentry',
            name='interpretation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
