# Generated by Django 5.2.9 on 2026-06-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_diary', '0002_dreamdiaryentry_interpretation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamdiaryentry',
            name='interpretation',
        ),
    ]
