// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteBlockItemViewData, DeleteBlockItemViewResponses, DownloadBlockByIdViewData, DownloadBlockByIdViewResponses, DownloadBlocksCountViewData, DownloadBlocksCountViewResponses, PaginationBlockViewData, PaginationBlockViewResponses, PostCreateBlockItemViewData, PostCreateBlockItemViewResponses, PostSampleWebsocketViewData, PostSampleWebsocketViewResponses, ReadBlockItemViewData, ReadBlockItemViewResponses, RunActionBuildBlockItemViewData, RunActionBuildBlockItemViewResponses, UpdateBlockItemViewData, UpdateBlockItemViewResponses, UploadDataToBlockByIdViewData, UploadDataToBlockByIdViewResponses, UploadFilesSumSizeViewData, UploadFilesSumSizeViewResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Pagination
 */
export const paginationBlockView = <ThrowOnError extends boolean = false>(options?: Options<PaginationBlockViewData, ThrowOnError>) => (options?.client ?? client).get<PaginationBlockViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/blocks/',
    ...options
});

/**
 * Post
 */
export const postCreateBlockItemView = <ThrowOnError extends boolean = false>(options: Options<PostCreateBlockItemViewData, ThrowOnError>) => (options.client ?? client).post<PostCreateBlockItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/blocks/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteBlockItemView = <ThrowOnError extends boolean = false>(options: Options<DeleteBlockItemViewData, ThrowOnError>) => (options.client ?? client).delete<DeleteBlockItemViewResponses, unknown, ThrowOnError>({
    url: '/api/blocks/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const readBlockItemView = <ThrowOnError extends boolean = false>(options: Options<ReadBlockItemViewData, ThrowOnError>) => (options.client ?? client).get<ReadBlockItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/blocks/{object_id}/',
    ...options
});

/**
 * Patch
 */
export const updateBlockItemView = <ThrowOnError extends boolean = false>(options: Options<UpdateBlockItemViewData, ThrowOnError>) => (options.client ?? client).patch<UpdateBlockItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/blocks/{object_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post
 */
export const runActionBuildBlockItemView = <ThrowOnError extends boolean = false>(options: Options<RunActionBuildBlockItemViewData, ThrowOnError>) => (options.client ?? client).post<RunActionBuildBlockItemViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/blocks/{object_id}/build/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get
 */
export const downloadBlockByIdView = <ThrowOnError extends boolean = false>(options: Options<DownloadBlockByIdViewData, ThrowOnError>) => (options.client ?? client).get<DownloadBlockByIdViewResponses, unknown, ThrowOnError>({ url: '/api/blocks/{object_id}/download/', ...options });

/**
 * Get
 */
export const uploadDataToBlockByIdView = <ThrowOnError extends boolean = false>(options: Options<UploadDataToBlockByIdViewData, ThrowOnError>) => (options.client ?? client).post<UploadDataToBlockByIdViewResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/blocks/{object_id}/upload/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get
 */
export const downloadBlocksCountView = <ThrowOnError extends boolean = false>(options?: Options<DownloadBlocksCountViewData, ThrowOnError>) => (options?.client ?? client).get<DownloadBlocksCountViewResponses, unknown, ThrowOnError>({ url: '/api/blocks/download-count/', ...options });

/**
 * Get
 */
export const uploadFilesSumSizeView = <ThrowOnError extends boolean = false>(options: Options<UploadFilesSumSizeViewData, ThrowOnError>) => (options.client ?? client).post<UploadFilesSumSizeViewResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/blocks/upload-sum-size/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Post
 */
export const postSampleWebsocketView = <ThrowOnError extends boolean = false>(options: Options<PostSampleWebsocketViewData, ThrowOnError>) => (options.client ?? client).post<PostSampleWebsocketViewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/blocks/websocket-test/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
