// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * BlockTypes
 */
export type BlockTypes = 'round' | 'square' | 'triangle';

/**
 * PaginationBlockFilterSchema
 */
export type PaginationBlockFilterSchema = {
    /**
     * A
     */
    a?: string | null;
    /**
     * C
     */
    c?: string | null;
    /**
     * Search
     */
    search?: string | null;
    block_type?: BlockTypes | null;
};

/**
 * PaginationQueryParams
 */
export type PaginationQueryParams = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Order By
     */
    order_by?: Array<string> | null;
    /**
     * Dict Filter
     */
    dict_filter?: string | null;
};

/**
 * EmptySchema
 */
export type EmptySchema = {
    [key: string]: unknown;
};

/**
 * BlockSchema
 */
export type BlockSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * A
     */
    a: string;
    /**
     * B
     */
    b: number;
    /**
     * C
     */
    c: boolean;
    block_type: BlockTypes;
};

/**
 * PaginationOutput[BlockSchema]
 */
export type PaginationOutputBlockSchema = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Pages Amount
     */
    pages_amount: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Data
     */
    data: Array<BlockSchema>;
};

/**
 * CreateBlockItemSchema
 */
export type CreateBlockItemSchema = {
    /**
     * A
     */
    a: string;
    /**
     * B
     */
    b: number;
    /**
     * C
     */
    c: boolean;
    block_type: BlockTypes;
};

/**
 * ItemByIdPath
 */
export type ItemByIdPath = {
    /**
     * Object Id
     */
    object_id: number;
};

/**
 * PatchBlockItemSchema
 */
export type PatchBlockItemSchema = {
    /**
     * A
     */
    a: string | null;
    /**
     * B
     */
    b: number | null;
    /**
     * C
     */
    c: boolean | null;
};

/**
 * RunActionBuildBlockItemSchema
 */
export type RunActionBuildBlockItemSchema = {
    /**
     * Should Build
     */
    should_build: boolean;
};

/**
 * UploadDataToBlockResponse
 */
export type UploadDataToBlockResponse = {
    /**
     * Total Size
     */
    total_size: number;
    block_type: BlockTypes;
};

/**
 * Schema
 */
export type Schema = {
    [key: string]: unknown;
};

/**
 * UploadFilesSumSizeResponse
 */
export type UploadFilesSumSizeResponse = {
    /**
     * Total Size
     */
    total_size: number;
};

/**
 * PostSampleWebsocketViewSchema
 */
export type PostSampleWebsocketViewSchema = {
    /**
     * Room Id
     */
    room_id: number;
};

export type PaginationBlockViewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Order By
         */
        order_by?: Array<string> | null;
        /**
         * Dict Filter
         */
        dict_filter?: string | null;
        /**
         * A
         */
        a?: string | null;
        /**
         * C
         */
        c?: string | null;
        /**
         * Search
         */
        search?: string | null;
        block_type?: BlockTypes | null;
    };
    url: '/api/blocks/';
};

export type PaginationBlockViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputBlockSchema;
};

export type PaginationBlockViewResponse = PaginationBlockViewResponses[keyof PaginationBlockViewResponses];

export type PostCreateBlockItemViewData = {
    body: CreateBlockItemSchema;
    path?: never;
    query?: never;
    url: '/api/blocks/';
};

export type PostCreateBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type PostCreateBlockItemViewResponse = PostCreateBlockItemViewResponses[keyof PostCreateBlockItemViewResponses];

export type DeleteBlockItemViewData = {
    body?: EmptySchema | null;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/';
};

export type DeleteBlockItemViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReadBlockItemViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/';
};

export type ReadBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type ReadBlockItemViewResponse = ReadBlockItemViewResponses[keyof ReadBlockItemViewResponses];

export type UpdateBlockItemViewData = {
    body: PatchBlockItemSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/';
};

export type UpdateBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type UpdateBlockItemViewResponse = UpdateBlockItemViewResponses[keyof UpdateBlockItemViewResponses];

export type RunActionBuildBlockItemViewData = {
    body: RunActionBuildBlockItemSchema;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/build/';
};

export type RunActionBuildBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type RunActionBuildBlockItemViewResponse = RunActionBuildBlockItemViewResponses[keyof RunActionBuildBlockItemViewResponses];

export type DownloadBlockByIdViewData = {
    body?: never;
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/download/';
};

export type DownloadBlockByIdViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UploadDataToBlockByIdViewData = {
    /**
     * FileParams
     */
    body: {
        /**
         * Files
         */
        files: Array<Blob | File>;
    };
    path: {
        /**
         * Object Id
         */
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/upload/';
};

export type UploadDataToBlockByIdViewResponses = {
    /**
     * OK
     */
    200: UploadDataToBlockResponse;
};

export type UploadDataToBlockByIdViewResponse = UploadDataToBlockByIdViewResponses[keyof UploadDataToBlockByIdViewResponses];

export type DownloadBlocksCountViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/blocks/download-count/';
};

export type DownloadBlocksCountViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UploadFilesSumSizeViewData = {
    /**
     * FileParams
     */
    body: {
        /**
         * Files
         */
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/blocks/upload-sum-size/';
};

export type UploadFilesSumSizeViewResponses = {
    /**
     * OK
     */
    200: UploadFilesSumSizeResponse;
};

export type UploadFilesSumSizeViewResponse = UploadFilesSumSizeViewResponses[keyof UploadFilesSumSizeViewResponses];

export type PostSampleWebsocketViewData = {
    body: PostSampleWebsocketViewSchema;
    path?: never;
    query?: never;
    url: '/api/blocks/websocket-test/';
};

export type PostSampleWebsocketViewResponses = {
    /**
     * OK
     */
    200: EmptySchema;
};

export type PostSampleWebsocketViewResponse = PostSampleWebsocketViewResponses[keyof PostSampleWebsocketViewResponses];
